export type Position = "PG" | "SG" | "SF" | "PF" | "C";

export type Player = {
  id: string;
  name: string;
  era: string;
  eraLabel: string;
  position: Position;
  jerseyNumber: string;
  ppg: number;
  rpg: number;
  apg: number;
  spg: number;
  bpg: number;
  rating: number;
  accolades: string;
}

export const ERA_LABELS: Record<string, string> = {
  "hickman": "The Hickman Era",
  "early":   "The Dromo Era",
  "crum":    "The Crum Dynasty",
  "pitino":  "The Pitino Era",
  "modern":  "The Modern Era",
};

export const ALL_ERAS = ["hickman", "early", "crum", "pitino", "modern"];

// Stats sourced from sports-reference.com/cbb — career per-game averages at Louisville.
// Pre-1973 steals/blocks were not officially tracked; those are set to 0.0.
// Players marked "stats from season logs" use per-season roster summaries, not individual career pages.
export const PLAYERS: Player[] = [

  // ── 1940s–1950s ──────────────────────────────────────────────────────────
  {
    id: "g-hauptfuhrer",
    name: "George Hauptfuhrer",
    era: "hickman",
    eraLabel: "The Hickman Era",
    position: "C",
    jerseyNumber: "13",
    ppg: 7.5,
    rpg: 5.5,
    apg: 0.5,
    spg: 0.0,
    bpg: 0.0,
    rating: 63,
    accolades: "OVC Conference (stats from season logs)"
  },
  {
    id: "k-reeves",
    name: "Kenny Reeves",
    era: "hickman",
    eraLabel: "The Hickman Era",
    position: "SG",
    jerseyNumber: "13",
    ppg: 10.5,
    rpg: 4.0,
    apg: 1.5,
    spg: 0.0,
    bpg: 0.0,
    rating: 68,
    accolades: "MVC Conference (stats from season logs)"
  },
  {
    id: "j-coleman",
    name: "Jack Coleman",
    era: "hickman",
    eraLabel: "The Hickman Era",
    position: "PF",
    jerseyNumber: "16",
    ppg: 14.0,
    rpg: 9.0,
    apg: 1.5,
    spg: 0.0,
    bpg: 0.0,
    rating: 78,
    accolades: "1949 NBA Draft (Rochester Royals), MVC All-Conference (stats from season logs)"
  },
  {
    id: "b-lochmueller",
    name: "Bob Lochmueller",
    era: "hickman",
    eraLabel: "The Hickman Era",
    position: "PF",
    jerseyNumber: "20",
    ppg: 13.5,
    rpg: 8.0,
    apg: 1.5,
    spg: 0.0,
    bpg: 0.0,
    rating: 75,
    accolades: "MVC Conference (stats from season logs)"
  },
  {
    id: "c-noble",
    name: "Chuck Noble",
    era: "hickman",
    eraLabel: "The Hickman Era",
    position: "SG",
    jerseyNumber: "16",
    ppg: 14.0,
    rpg: 5.0,
    apg: 2.5,
    spg: 0.0,
    bpg: 0.0,
    rating: 78,
    accolades: "MVC All-Conference, 1956 NBA Draft (Fort Wayne Pistons) (stats from season logs)"
  },
  {
    id: "p-rollins",
    name: "Phil Rollins",
    era: "hickman",
    eraLabel: "The Hickman Era",
    position: "PG",
    jerseyNumber: "9",
    ppg: 15.5,
    rpg: 4.5,
    apg: 3.0,
    spg: 0.0,
    bpg: 0.0,
    rating: 80,
    accolades: "MVC All-Conference, 1956 NBA Draft (Cincinnati Royals) (stats from season logs)"
  },
  {
    id: "j-morgan",
    name: "Jim Morgan",
    era: "hickman",
    eraLabel: "The Hickman Era",
    position: "SG",
    jerseyNumber: "12",
    ppg: 13.0,
    rpg: 4.0,
    apg: 2.5,
    spg: 0.0,
    bpg: 0.0,
    rating: 74,
    accolades: "MVC Conference (stats from season logs)"
  },
  {
    id: "c-tyra",
    name: "Charlie Tyra",
    era: "hickman",
    eraLabel: "The Hickman Era",
    position: "C",
    jerseyNumber: "8",
    ppg: 21.0,
    rpg: 17.5,
    apg: 1.5,
    spg: 0.0,
    bpg: 0.0,
    rating: 93,
    accolades: "2x Consensus All-American (1956-57), #8 Retired, 1957 NBA Draft #3 (Knicks)"
  },
  {
    id: "d-goldstein",
    name: "Don Goldstein",
    era: "hickman",
    eraLabel: "The Hickman Era",
    position: "PF",
    jerseyNumber: "24",
    ppg: 11.5,
    rpg: 7.5,
    apg: 1.5,
    spg: 0.0,
    bpg: 0.0,
    rating: 72,
    accolades: "MVC Conference (stats from season logs)"
  },
  {
    id: "j-turner",
    name: "John Turner",
    era: "hickman",
    eraLabel: "The Hickman Era",
    position: "PF",
    jerseyNumber: "22",
    ppg: 13.5,
    rpg: 9.0,
    apg: 1.5,
    spg: 0.0,
    bpg: 0.0,
    rating: 75,
    accolades: "MVC Conference, 1961 NBA Draft (St. Louis Hawks) (stats from season logs)"
  },

  // ── 1960s ────────────────────────────────────────────────────────────────
  {
    id: "w-unseld",
    name: "Wes Unseld",
    era: "hickman",
    eraLabel: "The Hickman Era",
    position: "C",
    jerseyNumber: "31",
    ppg: 20.6,
    rpg: 18.9,
    apg: 2.5,
    spg: 0.0,
    bpg: 0.0,
    rating: 99,
    accolades: "2x Consensus All-American, 1968 NBA Draft #2, Basketball HOF"
  },
  {
    id: "b-beard",
    name: "Butch Beard",
    era: "early",
    eraLabel: "The Dromo Era",
    position: "PG",
    jerseyNumber: "14",
    ppg: 19.0,
    rpg: 6.3,
    apg: 2.7,
    spg: 0.0,
    bpg: 0.0,
    rating: 86,
    accolades: "3x All-MVC, HS Parade AA, 1969 NBA Draft #10"
  },
  {
    id: "j-price",
    name: "Jim Price",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "SG",
    jerseyNumber: "15",
    ppg: 17.1,
    rpg: 4.8,
    apg: 4.3,
    spg: 0.0,
    bpg: 0.0,
    rating: 83,
    accolades: "2x NCAA All-American, 2x All-MVC, 1972 NBA Draft #16"
  },
  {
    id: "m-grosso",
    name: "Mike Grosso",
    era: "early",
    eraLabel: "The Dromo Era",
    position: "C",
    jerseyNumber: "20",
    ppg: 16.2,
    rpg: 14.3,
    apg: 1.8,
    spg: 0.0,
    bpg: 0.0,
    rating: 83,
    accolades: "2x All-MVC, 1969 & 1970 NBA Draft"
  },
  {
    id: "w-houston",
    name: "Wade Houston",
    era: "hickman",
    eraLabel: "The Hickman Era",
    position: "SF",
    jerseyNumber: "43",
    ppg: 13.5,
    rpg: 7.0,
    apg: 1.5,
    spg: 0.0,
    bpg: 0.0,
    rating: 79,
    accolades: "First Black scholarship athlete at Louisville, 1967 All-MVC"
  },
  {
    id: "b-olsen",
    name: "Bud Olsen",
    era: "hickman",
    eraLabel: "The Hickman Era",
    position: "C",
    jerseyNumber: "13",
    ppg: 13.0,
    rpg: 10.5,
    apg: 1.5,
    spg: 0.0,
    bpg: 0.0,
    rating: 77,
    accolades: "All-MVC, 1962 NBA Draft, Cincinnati Royals"
  },
  {
    id: "j-king-60",
    name: "Jerry King",
    era: "early",
    eraLabel: "The Dromo Era",
    position: "PF",
    jerseyNumber: "32",
    ppg: 13.8,
    rpg: 5.5,
    apg: 1.5,
    spg: 0.0,
    bpg: 0.0,
    rating: 77,
    accolades: "All-MVC, 1968 Final Four (stats from season logs)"
  },
  {
    id: "r-thomas-60",
    name: "Ron Thomas",
    era: "early",
    eraLabel: "The Dromo Era",
    position: "SG",
    jerseyNumber: "35",
    ppg: 9.5,
    rpg: 3.5,
    apg: 1.8,
    spg: 0.0,
    bpg: 0.0,
    rating: 73,
    accolades: "MVC All-Conference, 1973 NBA Draft (stats from season logs)"
  },
  {
    id: "f-holden",
    name: "Fred Holden",
    era: "early",
    eraLabel: "The Dromo Era",
    position: "SG",
    jerseyNumber: "24",
    ppg: 10.5,
    rpg: 3.8,
    apg: 2.0,
    spg: 0.0,
    bpg: 0.0,
    rating: 74,
    accolades: "MVC All-Conference (stats from season logs)"
  },
  {
    id: "h-bacon",
    name: "Henry Bacon",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "SG",
    jerseyNumber: "32",
    ppg: 10.5,
    rpg: 3.5,
    apg: 1.8,
    spg: 0.0,
    bpg: 0.0,
    rating: 73,
    accolades: "MVC Conference (stats from season logs)"
  },
  {
    id: "m-lawhon",
    name: "Mike Lawhon",
    era: "early",
    eraLabel: "The Dromo Era",
    position: "SF",
    jerseyNumber: "33",
    ppg: 9.5,
    rpg: 5.2,
    apg: 1.2,
    spg: 0.0,
    bpg: 0.0,
    rating: 72,
    accolades: "MVC Conference (stats from season logs)"
  },
  {
    id: "e-whitehead",
    name: "Eddie Whitehead",
    era: "hickman",
    eraLabel: "The Hickman Era",
    position: "PF",
    jerseyNumber: "24",
    ppg: 8.8,
    rpg: 5.5,
    apg: 0.8,
    spg: 0.0,
    bpg: 0.0,
    rating: 71,
    accolades: "MVC Conference (stats from season logs)"
  },
  {
    id: "d-gilbert",
    name: "Dave Gilbert",
    era: "early",
    eraLabel: "The Dromo Era",
    position: "PG",
    jerseyNumber: "20",
    ppg: 8.0,
    rpg: 2.8,
    apg: 3.0,
    spg: 0.0,
    bpg: 0.0,
    rating: 71,
    accolades: "MVC Conference (stats from season logs)"
  },
  {
    id: "d-paulette",
    name: "Dennis Paulette",
    era: "early",
    eraLabel: "The Dromo Era",
    position: "PF",
    jerseyNumber: "55",
    ppg: 8.5,
    rpg: 5.5,
    apg: 1.0,
    spg: 0.0,
    bpg: 0.0,
    rating: 71,
    accolades: "MVC Conference (stats from season logs)"
  },
  {
    id: "a-vilcheck",
    name: "Al Vilcheck",
    era: "early",
    eraLabel: "The Dromo Era",
    position: "C",
    jerseyNumber: "52",
    ppg: 7.5,
    rpg: 5.8,
    apg: 0.8,
    spg: 0.0,
    bpg: 0.0,
    rating: 70,
    accolades: "MVC Conference (stats from season logs)"
  },
  {
    id: "m-selvy",
    name: "Marv Selvy",
    era: "early",
    eraLabel: "The Dromo Era",
    position: "SF",
    jerseyNumber: "32",
    ppg: 7.2,
    rpg: 4.5,
    apg: 0.8,
    spg: 0.0,
    bpg: 0.0,
    rating: 70,
    accolades: "MVC Conference (stats from season logs)"
  },
  {
    id: "b-gorius",
    name: "Bob Gorius",
    era: "early",
    eraLabel: "The Dromo Era",
    position: "PF",
    jerseyNumber: "45",
    ppg: 7.0,
    rpg: 5.0,
    apg: 0.8,
    spg: 0.0,
    bpg: 0.0,
    rating: 70,
    accolades: "MVC Conference (stats from season logs)"
  },
  {
    id: "j-liedtke",
    name: "Joe Liedtke",
    era: "hickman",
    eraLabel: "The Hickman Era",
    position: "C",
    jerseyNumber: "53",
    ppg: 6.8,
    rpg: 5.5,
    apg: 0.8,
    spg: 0.0,
    bpg: 0.0,
    rating: 69,
    accolades: "MVC Conference (stats from season logs)"
  },
  {
    id: "d-deeken",
    name: "Denny Deeken",
    era: "early",
    eraLabel: "The Dromo Era",
    position: "PG",
    jerseyNumber: "11",
    ppg: 5.8,
    rpg: 2.5,
    apg: 2.5,
    spg: 0.0,
    bpg: 0.0,
    rating: 69,
    accolades: "MVC Conference (stats from season logs)"
  },
  {
    id: "l-carter-60",
    name: "Larry Carter",
    era: "early",
    eraLabel: "The Dromo Era",
    position: "PG",
    jerseyNumber: "10",
    ppg: 6.5,
    rpg: 2.5,
    apg: 2.5,
    spg: 0.0,
    bpg: 0.0,
    rating: 68,
    accolades: "MVC Conference (stats from season logs)"
  },

  // ── 1970s ────────────────────────────────────────────────────────────────
  {
    id: "d-griffith",
    name: "Darrell Griffith",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "SG",
    jerseyNumber: "35",
    ppg: 18.5,
    rpg: 4.6,
    apg: 3.0,
    spg: 2.0,
    bpg: 0.8,
    rating: 98,
    accolades: "1980 NCAA Champion, Wooden Award, NBA Draft #2"
  },
  {
    id: "j-bridgeman",
    name: "Junior Bridgeman",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "SF",
    jerseyNumber: "10",
    ppg: 15.5,
    rpg: 7.6,
    apg: 2.7,
    spg: 0.9,
    bpg: 0.4,
    rating: 92,
    accolades: "2x MVC POY, 3x All-MVC, 1975 NBA Draft #8"
  },
  {
    id: "a-murphy",
    name: "Allen Murphy",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "SF",
    jerseyNumber: "20",
    ppg: 16.3,
    rpg: 5.1,
    apg: 1.8,
    spg: 0.9,
    bpg: 1.1,
    rating: 88,
    accolades: "1975 Final Four, 2x All-MVC, 1975 NBA Draft #17"
  },
  {
    id: "w-cox",
    name: "Wesley Cox",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "SF",
    jerseyNumber: "41",
    ppg: 14.0,
    rpg: 7.4,
    apg: 2.4,
    spg: 1.0,
    bpg: 0.5,
    rating: 81,
    accolades: "HS Parade AA, 1977 NBA Draft #18"
  },
  {
    id: "t-howard",
    name: "Terry Howard",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "SG",
    jerseyNumber: "21",
    ppg: 12.0,
    rpg: 3.0,
    apg: 2.0,
    spg: 0.8,
    bpg: 0.2,
    rating: 82,
    accolades: "1975 NCAA Final Four, All-MVC"
  },
  {
    id: "r-gallon",
    name: "Ricky Gallon",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "C",
    jerseyNumber: "54",
    ppg: 11.6,
    rpg: 6.6,
    apg: 0.6,
    spg: 0.5,
    bpg: 1.5,
    rating: 79,
    accolades: "1978 NBA Draft 3rd round"
  },
  {
    id: "p-bond",
    name: "Phil Bond",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "PG",
    jerseyNumber: "30",
    ppg: 10.8,
    rpg: 3.1,
    apg: 5.2,
    spg: 1.1,
    bpg: 0.1,
    rating: 80,
    accolades: "1975 Final Four, All-MVC, MVC All-Tournament"
  },
  {
    id: "l-williams-70",
    name: "Larry Williams",
    era: "early",
    eraLabel: "The Dromo Era",
    position: "PF",
    jerseyNumber: "44",
    ppg: 11.3,
    rpg: 7.8,
    apg: 1.2,
    spg: 0.6,
    bpg: 0.9,
    rating: 78,
    accolades: "All-MVC Honorable Mention (stats from season logs)"
  },
  {
    id: "r-burkman",
    name: "Roger Burkman",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "SG",
    jerseyNumber: "34",
    ppg: 7.5,
    rpg: 3.5,
    apg: 2.0,
    spg: 1.2,
    bpg: 0.2,
    rating: 75,
    accolades: "1980 NCAA Champion (stats from season logs)"
  },
  {
    id: "r-wilson-70",
    name: "Rick Wilson",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "SG",
    jerseyNumber: "42",
    ppg: 7.5,
    rpg: 3.5,
    apg: 1.8,
    spg: 1.0,
    bpg: 0.2,
    rating: 74,
    accolades: "All-MVC Honorable Mention (stats from season logs)"
  },
  {
    id: "b-bunton",
    name: "Bill Bunton",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "C",
    jerseyNumber: "53",
    ppg: 9.0,
    rpg: 7.0,
    apg: 0.8,
    spg: 0.6,
    bpg: 1.0,
    rating: 74,
    accolades: "MVC All-Conference (stats from season logs)"
  },
  {
    id: "b-butler-70",
    name: "Bill Butler",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "PF",
    jerseyNumber: "40",
    ppg: 9.5,
    rpg: 6.0,
    apg: 1.0,
    spg: 0.8,
    bpg: 0.5,
    rating: 74,
    accolades: "MVC Conference (stats from season logs)"
  },
  {
    id: "p-wright",
    name: "Poncho Wright",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "SF",
    jerseyNumber: "44",
    ppg: 6.5,
    rpg: 4.0,
    apg: 1.0,
    spg: 0.8,
    bpg: 0.3,
    rating: 71,
    accolades: "1980 NCAA Champion (stats from season logs)"
  },
  {
    id: "b-turner-70",
    name: "Bobby Turner",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "SF",
    jerseyNumber: "25",
    ppg: 7.0,
    rpg: 4.5,
    apg: 1.0,
    spg: 0.9,
    bpg: 0.3,
    rating: 71,
    accolades: "Metro Conference (stats from season logs)"
  },
  {
    id: "t-branch-70",
    name: "Tony Branch",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "PG",
    jerseyNumber: "11",
    ppg: 5.0,
    rpg: 2.0,
    apg: 2.5,
    spg: 0.9,
    bpg: 0.1,
    rating: 69,
    accolades: "1980 NCAA Champion (stats from season logs)"
  },
  {
    id: "k-bradley-70",
    name: "Ken Bradley",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "C",
    jerseyNumber: "50",
    ppg: 7.0,
    rpg: 6.5,
    apg: 0.8,
    spg: 0.5,
    bpg: 0.8,
    rating: 71,
    accolades: "MVC Conference (stats from season logs)"
  },
  {
    id: "d-brown-70",
    name: "Danny Brown",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "SG",
    jerseyNumber: "12",
    ppg: 6.0,
    rpg: 2.5,
    apg: 2.0,
    spg: 0.9,
    bpg: 0.1,
    rating: 72,
    accolades: "MVC Conference (stats from season logs)"
  },
  {
    id: "i-whitfield",
    name: "Ike Whitfield",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "PF",
    jerseyNumber: "43",
    ppg: 6.0,
    rpg: 5.0,
    apg: 0.8,
    spg: 0.7,
    bpg: 0.4,
    rating: 70,
    accolades: "MVC Conference (stats from season logs)"
  },
  {
    id: "d-cleveland",
    name: "Daryl Cleveland",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "PF",
    jerseyNumber: "24",
    ppg: 5.5,
    rpg: 4.5,
    apg: 0.8,
    spg: 0.7,
    bpg: 0.3,
    rating: 70,
    accolades: "Metro Conference (stats from season logs)"
  },
  {
    id: "m-pulliam",
    name: "Marty Pulliam",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "C",
    jerseyNumber: "51",
    ppg: 5.5,
    rpg: 5.0,
    apg: 0.5,
    spg: 0.5,
    bpg: 0.8,
    rating: 69,
    accolades: "1980 NCAA Champion (stats from season logs)"
  },
  {
    id: "j-ellis-70",
    name: "Jim Ellis",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "PG",
    jerseyNumber: "20",
    ppg: 5.0,
    rpg: 1.8,
    apg: 2.5,
    spg: 0.8,
    bpg: 0.1,
    rating: 68,
    accolades: "Metro Conference (stats from season logs)"
  },

  // ── 1980s ────────────────────────────────────────────────────────────────
  {
    id: "l-gordon",
    name: "Lancaster Gordon",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "PG",
    jerseyNumber: "4",
    ppg: 14.2,
    rpg: 3.5,
    apg: 5.8,
    spg: 1.5,
    bpg: 0.2,
    rating: 83,
    accolades: "1984 NBA Draft #12 (LA Clippers), 3x Metro Conference All-Tournament"
  },
  {
    id: "p-ellison",
    name: "Pervis Ellison",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "C",
    jerseyNumber: "43",
    ppg: 15.8,
    rpg: 8.4,
    apg: 2.4,
    spg: 1.3,
    bpg: 2.8,
    rating: 96,
    accolades: "1986 NCAA Champion & MOP, 1989 NBA Draft #1"
  },
  {
    id: "m-wagner",
    name: "Milt Wagner",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "PG",
    jerseyNumber: "20",
    ppg: 12.8,
    rpg: 2.5,
    apg: 3.0,
    spg: 1.0,
    bpg: 0.4,
    rating: 88,
    accolades: "1986 NCAA Champion, 1983 All-American"
  },
  {
    id: "b-thompson",
    name: "Billy Thompson",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "SF",
    jerseyNumber: "40",
    ppg: 11.8,
    rpg: 6.5,
    apg: 3.2,
    spg: 0.8,
    bpg: 1.3,
    rating: 89,
    accolades: "1986 NCAA Champion & All-American, 1986 NBA Draft #19"
  },
  {
    id: "d-smith-80",
    name: "Derek Smith",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "SG",
    jerseyNumber: "43",
    ppg: 13.9,
    rpg: 6.7,
    apg: 1.9,
    spg: 1.1,
    bpg: 0.5,
    rating: 89,
    accolades: "1980 NCAA Champion, 1982 All-American, Metro POY"
  },
  {
    id: "r-mccray",
    name: "Rodney McCray",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "PF",
    jerseyNumber: "22",
    ppg: 9.2,
    rpg: 7.6,
    apg: 2.6,
    spg: 1.1,
    bpg: 1.3,
    rating: 85,
    accolades: "1980 NCAA Champion, 1982-83 Metro POY, 1983 NBA Draft #3"
  },
  {
    id: "s-mccray",
    name: "Scooter McCray",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "PF",
    jerseyNumber: "21",
    ppg: 7.6,
    rpg: 5.5,
    apg: 2.7,
    spg: 1.3,
    bpg: 1.0,
    rating: 80,
    accolades: "1980 NCAA Champion, 1982-83 All-American, 1983 NBA Draft #36"
  },
  {
    id: "j-eaves",
    name: "Jerry Eaves",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "PG",
    jerseyNumber: "5",
    ppg: 9.7,
    rpg: 1.8,
    apg: 2.6,
    spg: 1.0,
    bpg: 0.0,
    rating: 79,
    accolades: "1980 NCAA Champion, HS Parade AA, 1982 NBA Draft"
  },
  {
    id: "w-brown-80",
    name: "Wiley Brown",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "PF",
    jerseyNumber: "41",
    ppg: 5.7,
    rpg: 3.3,
    apg: 1.0,
    spg: 1.0,
    bpg: 0.6,
    rating: 78,
    accolades: "1980 NCAA Champion, 1979-80 All-Metro"
  },
  {
    id: "l-smith",
    name: "LaBradford Smith",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "SG",
    jerseyNumber: "21",
    ppg: 13.6,
    rpg: 2.9,
    apg: 5.4,
    spg: 1.7,
    bpg: 0.1,
    rating: 89,
    accolades: "HS Parade AA, 1991 NBA Draft #19"
  },
  {
    id: "k-payne",
    name: "Kenny Payne",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "SF",
    jerseyNumber: "21",
    ppg: 8.5,
    rpg: 3.7,
    apg: 1.1,
    spg: 0.8,
    bpg: 1.0,
    rating: 80,
    accolades: "1986 NCAA Champion, HS Parade AA, 1989 NBA Draft #19"
  },
  {
    id: "h-crook",
    name: "Herbert Crook",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "PF",
    jerseyNumber: "41",
    ppg: 10.7,
    rpg: 6.4,
    apg: 2.1,
    spg: 0.8,
    bpg: 0.5,
    rating: 82,
    accolades: "1986 NCAA Champion"
  },
  {
    id: "f-spencer",
    name: "Felton Spencer",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "C",
    jerseyNumber: "52",
    ppg: 8.7,
    rpg: 5.2,
    apg: 0.7,
    spg: 0.7,
    bpg: 0.4,
    rating: 79,
    accolades: "HS Parade AA, 1990 NBA Draft #6"
  },
  {
    id: "e-sullivan",
    name: "Everick Sullivan",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "SG",
    jerseyNumber: "34",
    ppg: 12.6,
    rpg: 3.9,
    apg: 3.1,
    spg: 1.2,
    bpg: 0.3,
    rating: 82,
    accolades: "HS Parade AA, Metro All-Conference"
  },
  {
    id: "t-kimbro",
    name: "Tony Kimbro",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "SF",
    jerseyNumber: "44",
    ppg: 7.5,
    rpg: 4.5,
    apg: 1.2,
    spg: 0.8,
    bpg: 0.4,
    rating: 74,
    accolades: "1986 NCAA Champion (stats from season logs)"
  },
  {
    id: "j-hall-80",
    name: "Jeff Hall",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "PG",
    jerseyNumber: "42",
    ppg: 7.0,
    rpg: 2.5,
    apg: 3.0,
    spg: 1.0,
    bpg: 0.1,
    rating: 74,
    accolades: "1986 NCAA Champion (stats from season logs)"
  },
  {
    id: "k-williams-80",
    name: "Keith Williams",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "SG",
    jerseyNumber: "11",
    ppg: 7.5,
    rpg: 3.0,
    apg: 1.5,
    spg: 1.0,
    bpg: 0.2,
    rating: 73,
    accolades: "Metro All-Conference (stats from season logs)"
  },
  {
    id: "c-holden-80",
    name: "Cornelius Holden",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "C",
    jerseyNumber: "30",
    ppg: 5.5,
    rpg: 4.5,
    apg: 0.8,
    spg: 0.5,
    bpg: 1.0,
    rating: 71,
    accolades: "Metro Conference (stats from season logs)"
  },
  {
    id: "b-sumpter",
    name: "Barry Sumpter",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "C",
    jerseyNumber: "11",
    ppg: 6.0,
    rpg: 5.5,
    apg: 0.5,
    spg: 0.4,
    bpg: 1.2,
    rating: 72,
    accolades: "Metro Conference (stats from season logs)"
  },
  {
    id: "r-valentine",
    name: "Robbie Valentine",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "PG",
    jerseyNumber: "00",
    ppg: 5.5,
    rpg: 2.0,
    apg: 2.5,
    spg: 0.9,
    bpg: 0.1,
    rating: 71,
    accolades: "Metro Conference (stats from season logs)"
  },
  {
    id: "p-williams-80",
    name: "Perky Williams",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "SF",
    jerseyNumber: "44",
    ppg: 7.0,
    rpg: 4.0,
    apg: 1.0,
    spg: 0.9,
    bpg: 0.3,
    rating: 73,
    accolades: "Metro All-Freshman (stats from season logs)"
  },

  // ── 1990s ────────────────────────────────────────────────────────────────
  {
    id: "d-wheat",
    name: "DeJuan Wheat",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "PG",
    jerseyNumber: "32",
    ppg: 16.1,
    rpg: 2.6,
    apg: 3.7,
    spg: 1.5,
    bpg: 0.2,
    rating: 93,
    accolades: "1997 All-CUSA, HS Parade AA, 1997 NBA Draft"
  },
  {
    id: "c-rozier",
    name: "Clifford Rozier",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "PF",
    jerseyNumber: "44",
    ppg: 17.0,
    rpg: 11.0,
    apg: 1.8,
    spg: 1.0,
    bpg: 1.8,
    rating: 91,
    accolades: "1994 Consensus All-American, 2x Metro POY, 1994 NBA Draft #16"
  },
  {
    id: "d-morton",
    name: "Dwayne Morton",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "SF",
    jerseyNumber: "40",
    ppg: 15.0,
    rpg: 4.2,
    apg: 1.9,
    spg: 1.2,
    bpg: 0.8,
    rating: 81,
    accolades: "HS Parade AA, 1994 NBA Draft #45"
  },
  {
    id: "g-minor",
    name: "Greg Minor",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "SG",
    jerseyNumber: "21",
    ppg: 12.6,
    rpg: 5.6,
    apg: 2.4,
    spg: 1.3,
    bpg: 0.3,
    rating: 81,
    accolades: "HS Parade AA, 1994 NBA Draft #25"
  },
  {
    id: "s-walker",
    name: "Samaki Walker",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "C",
    jerseyNumber: "54",
    ppg: 14.3,
    rpg: 7.3,
    apg: 1.2,
    spg: 0.7,
    bpg: 2.4,
    rating: 87,
    accolades: "HS Parade AA, 1996 NBA Draft #9"
  },
  {
    id: "a-sims",
    name: "Alvin Sims",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "SG",
    jerseyNumber: "5",
    ppg: 8.3,
    rpg: 3.9,
    apg: 1.9,
    spg: 1.7,
    bpg: 0.4,
    rating: 76,
    accolades: "1996-97 All-CUSA, 1996-97 CUSA DPOY"
  },
  {
    id: "e-slay",
    name: "Eric Slay",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "SG",
    jerseyNumber: "12",
    ppg: 11.3,
    rpg: 3.4,
    apg: 2.4,
    spg: 1.4,
    bpg: 0.2,
    rating: 80,
    accolades: "C-USA All-Freshman, All-CUSA Honorable Mention"
  },
  {
    id: "a-watkins",
    name: "Alvin Watkins",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "SF",
    jerseyNumber: "33",
    ppg: 10.8,
    rpg: 5.7,
    apg: 1.6,
    spg: 1.0,
    bpg: 0.6,
    rating: 78,
    accolades: "Metro Conference All-Freshman"
  },
  {
    id: "d-dantzler",
    name: "Damion Dantzler",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "SF",
    jerseyNumber: "22",
    ppg: 8.0,
    rpg: 4.5,
    apg: 1.2,
    spg: 0.9,
    bpg: 0.3,
    rating: 74,
    accolades: "C-USA Conference (stats from season logs)"
  },
  {
    id: "b-kiser",
    name: "Brian Kiser",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "PF",
    jerseyNumber: "3",
    ppg: 6.5,
    rpg: 5.5,
    apg: 1.0,
    spg: 0.7,
    bpg: 0.5,
    rating: 71,
    accolades: "C-USA Conference (stats from season logs)"
  },
  {
    id: "a-sanders",
    name: "Alex Sanders",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "PF",
    jerseyNumber: "44",
    ppg: 7.5,
    rpg: 5.5,
    apg: 1.0,
    spg: 0.9,
    bpg: 0.5,
    rating: 73,
    accolades: "C-USA Conference (stats from season logs)"
  },
  {
    id: "c-murray",
    name: "Cameron Murray",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "PG",
    jerseyNumber: "15",
    ppg: 7.5,
    rpg: 2.5,
    apg: 3.0,
    spg: 1.1,
    bpg: 0.1,
    rating: 72,
    accolades: "C-USA Conference (stats from season logs)"
  },
  {
    id: "n-johnson-90",
    name: "Nate Johnson",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "SF",
    jerseyNumber: "21",
    ppg: 7.0,
    rpg: 4.5,
    apg: 1.0,
    spg: 0.8,
    bpg: 0.3,
    rating: 72,
    accolades: "C-USA Conference (stats from season logs)"
  },
  {
    id: "t-williams-90",
    name: "Tony Williams",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "PF",
    jerseyNumber: "3",
    ppg: 7.5,
    rpg: 4.5,
    apg: 1.0,
    spg: 0.8,
    bpg: 0.4,
    rating: 72,
    accolades: "C-USA Conference (stats from season logs)"
  },
  {
    id: "m-maybin",
    name: "Marques Maybin",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "SG",
    jerseyNumber: "5",
    ppg: 7.5,
    rpg: 3.0,
    apg: 2.5,
    spg: 1.1,
    bpg: 0.1,
    rating: 72,
    accolades: "C-USA Conference (stats from season logs)"
  },
  {
    id: "d-edward",
    name: "Dion Edward",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "C",
    jerseyNumber: "51",
    ppg: 6.5,
    rpg: 6.0,
    apg: 0.8,
    spg: 0.5,
    bpg: 1.2,
    rating: 72,
    accolades: "C-USA Conference (stats from season logs)"
  },
  {
    id: "k-legree",
    name: "Keith LeGree",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "SG",
    jerseyNumber: "5",
    ppg: 6.0,
    rpg: 2.5,
    apg: 1.5,
    spg: 0.8,
    bpg: 0.2,
    rating: 70,
    accolades: "Metro All-Freshman (stats from season logs)"
  },
  {
    id: "k-smiley",
    name: "Kevin Smiley",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "PG",
    jerseyNumber: "13",
    ppg: 5.5,
    rpg: 2.0,
    apg: 2.5,
    spg: 0.9,
    bpg: 0.1,
    rating: 70,
    accolades: "C-USA Conference (stats from season logs)"
  },
  {
    id: "e-johnson-90",
    name: "Eric Johnson",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "SF",
    jerseyNumber: "43",
    ppg: 6.5,
    rpg: 4.0,
    apg: 1.0,
    spg: 0.8,
    bpg: 0.3,
    rating: 71,
    accolades: "C-USA Conference (stats from season logs)"
  },
  {
    id: "bj-flynn",
    name: "B.J. Flynn",
    era: "crum",
    eraLabel: "The Crum Dynasty",
    position: "PG",
    jerseyNumber: "13",
    ppg: 5.8,
    rpg: 2.0,
    apg: 2.8,
    spg: 0.9,
    bpg: 0.1,
    rating: 70,
    accolades: "C-USA Conference (stats from season logs)"
  },

  // ── 2000s ────────────────────────────────────────────────────────────────
  {
    id: "r-gaines",
    name: "Reece Gaines",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "SG",
    jerseyNumber: "22",
    ppg: 15.6,
    rpg: 3.4,
    apg: 3.8,
    spg: 1.5,
    bpg: 0.2,
    rating: 91,
    accolades: "2x All-CUSA, 2003 NBA Draft #15"
  },
  {
    id: "f-garcia",
    name: "Francisco Garcia",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "SF",
    jerseyNumber: "32",
    ppg: 14.4,
    rpg: 3.9,
    apg: 3.5,
    spg: 1.5,
    bpg: 1.4,
    rating: 90,
    accolades: "CUSA ROY, 3x All-CUSA, 2005 NBA Draft #23"
  },
  {
    id: "t-williams-00",
    name: "Terrence Williams",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "SF",
    jerseyNumber: "1",
    ppg: 11.2,
    rpg: 6.9,
    apg: 3.9,
    spg: 1.5,
    bpg: 0.6,
    rating: 89,
    accolades: "3x All-Big East, 2009 NBA Draft #11"
  },
  {
    id: "t-dean",
    name: "Taquan Dean",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "SG",
    jerseyNumber: "5",
    ppg: 12.9,
    rpg: 4.2,
    apg: 2.4,
    spg: 0.9,
    bpg: 0.0,
    rating: 81,
    accolades: "2004-05 NCAA All-Region, All-CUSA, 2005-06 Big East"
  },
  {
    id: "earl-clark",
    name: "Earl Clark",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "SF",
    jerseyNumber: "5",
    ppg: 10.6,
    rpg: 7.0,
    apg: 1.7,
    spg: 0.9,
    bpg: 1.2,
    rating: 83,
    accolades: "2x NCAA All-Region, 2009 All-Big East, 2009 NBA Draft #14"
  },
  {
    id: "s-samuels",
    name: "Samardo Samuels",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "C",
    jerseyNumber: "24",
    ppg: 13.5,
    rpg: 5.9,
    apg: 1.1,
    spg: 0.6,
    bpg: 1.2,
    rating: 79,
    accolades: "HS Parade AA, 2009-10 All-Big East"
  },
  {
    id: "l-obannon",
    name: "Larry O'Bannon",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "SF",
    jerseyNumber: "34",
    ppg: 8.8,
    rpg: 2.4,
    apg: 1.5,
    spg: 0.7,
    bpg: 0.2,
    rating: 77,
    accolades: "2004-05 NCAA All-Region team"
  },
  {
    id: "e-myles",
    name: "Ellis Myles",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "PF",
    jerseyNumber: "2",
    ppg: 8.4,
    rpg: 8.0,
    apg: 2.2,
    spg: 1.1,
    bpg: 0.7,
    rating: 78,
    accolades: "2004-05 NCAA All-Region team, CUSA All-Conference"
  },
  {
    id: "e-sosa",
    name: "Edgar Sosa",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "PG",
    jerseyNumber: "10",
    ppg: 9.7,
    rpg: 1.8,
    apg: 2.8,
    spg: 0.8,
    bpg: 0.1,
    rating: 80,
    accolades: "2007 Big East All-Freshman, Big East Tourney champion"
  },
  {
    id: "j-palacios",
    name: "Juan Palacios",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "PF",
    jerseyNumber: "3",
    ppg: 8.9,
    rpg: 5.7,
    apg: 1.3,
    spg: 0.9,
    bpg: 0.4,
    rating: 79,
    accolades: "2005 All-CUSA, Big East Honorable Mention"
  },
  {
    id: "d-padgett-00",
    name: "David Padgett",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "C",
    jerseyNumber: "4",
    ppg: 8.8,
    rpg: 5.1,
    apg: 1.6,
    spg: 0.5,
    bpg: 1.2,
    rating: 80,
    accolades: "Big East All-Tournament Team 2005"
  },
  {
    id: "b-jenkins-00",
    name: "Brandon Jenkins",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "SG",
    jerseyNumber: "11",
    ppg: 7.5,
    rpg: 2.5,
    apg: 1.5,
    spg: 1.0,
    bpg: 0.2,
    rating: 74,
    accolades: "Big East Conference (stats from season logs)"
  },
  {
    id: "l-wade-00",
    name: "Lorrenzo Wade",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "SF",
    jerseyNumber: "1",
    ppg: 6.5,
    rpg: 4.0,
    apg: 1.0,
    spg: 0.8,
    bpg: 0.3,
    rating: 73,
    accolades: "CUSA Conference (stats from season logs)"
  },
  {
    id: "a-mcgee-00",
    name: "Andre McGee",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "PG",
    jerseyNumber: "33",
    ppg: 5.5,
    rpg: 1.8,
    apg: 2.5,
    spg: 1.0,
    bpg: 0.1,
    rating: 72,
    accolades: "Big East Conference (stats from season logs)"
  },
  {
    id: "j-smith-00",
    name: "Jerry Smith",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "PG",
    jerseyNumber: "34",
    ppg: 6.5,
    rpg: 1.5,
    apg: 2.8,
    spg: 1.1,
    bpg: 0.1,
    rating: 72,
    accolades: "Big East Conference (stats from season logs)"
  },
  {
    id: "o-george-00",
    name: "Otis George",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "PF",
    jerseyNumber: "42",
    ppg: 7.0,
    rpg: 5.5,
    apg: 0.8,
    spg: 0.7,
    bpg: 0.5,
    rating: 73,
    accolades: "CUSA Conference (stats from season logs)"
  },
  {
    id: "p-knowles",
    name: "Preston Knowles",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "PG",
    jerseyNumber: "2",
    ppg: 9.5,
    rpg: 2.5,
    apg: 2.5,
    spg: 1.2,
    bpg: 0.1,
    rating: 76,
    accolades: "Big East All-Tournament Team (stats from season logs)"
  },
  {
    id: "t-jennings-00",
    name: "Terrence Jennings",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "PF",
    jerseyNumber: "23",
    ppg: 6.0,
    rpg: 5.0,
    apg: 0.5,
    spg: 0.5,
    bpg: 1.0,
    rating: 72,
    accolades: "Big East Conference (stats from season logs)"
  },
  {
    id: "p-johnson-00",
    name: "Perrin Johnson",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "SG",
    jerseyNumber: "15",
    ppg: 5.0,
    rpg: 1.5,
    apg: 1.5,
    spg: 0.9,
    bpg: 0.1,
    rating: 70,
    accolades: "CUSA Conference (stats from season logs)"
  },
  {
    id: "b-johnson-00",
    name: "Brian Johnson",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "C",
    jerseyNumber: "44",
    ppg: 5.5,
    rpg: 5.0,
    apg: 0.8,
    spg: 0.4,
    bpg: 0.8,
    rating: 70,
    accolades: "Big East Conference (stats from season logs)"
  },

  // ── 2010s ────────────────────────────────────────────────────────────────
  {
    id: "r-smith",
    name: "Russ Smith",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "PG",
    jerseyNumber: "2",
    ppg: 14.3,
    rpg: 2.7,
    apg: 2.8,
    spg: 1.9,
    bpg: 0.1,
    rating: 95,
    accolades: "2013 NCAA Champion, 2x All-American ('Russdiculous')"
  },
  {
    id: "p-siva",
    name: "Peyton Siva",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "PG",
    jerseyNumber: "3",
    ppg: 8.4,
    rpg: 2.4,
    apg: 4.7,
    spg: 1.8,
    bpg: 0.1,
    rating: 89,
    accolades: "2013 NCAA Champion, 2x All-Big East Tourney MVP"
  },
  {
    id: "d-mitchell",
    name: "Donovan Mitchell",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "SG",
    jerseyNumber: "45",
    ppg: 11.7,
    rpg: 4.1,
    apg: 2.2,
    spg: 1.5,
    bpg: 0.3,
    rating: 90,
    accolades: "2017 All-ACC, 2017 NBA Draft #13, 5x NBA All-Star"
  },
  {
    id: "m-harrell",
    name: "Montrezl Harrell",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "PF",
    jerseyNumber: "24",
    ppg: 11.6,
    rpg: 6.9,
    apg: 0.9,
    spg: 0.8,
    bpg: 1.1,
    rating: 91,
    accolades: "2013 NCAA Champion, 2015 Karl Malone Award"
  },
  {
    id: "g-dieng",
    name: "Gorgui Dieng",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "C",
    jerseyNumber: "10",
    ppg: 8.3,
    rpg: 7.9,
    apg: 1.2,
    spg: 1.0,
    bpg: 2.6,
    rating: 88,
    accolades: "2013 NCAA Champion, Big East DPOY, NBA Draft #21"
  },
  {
    id: "l-hancock",
    name: "Luke Hancock",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "SF",
    jerseyNumber: "11",
    ppg: 10.1,
    rpg: 2.6,
    apg: 1.8,
    spg: 1.0,
    bpg: 0.1,
    rating: 85,
    accolades: "2013 Final Four MOP, 2013 NCAA Champion"
  },
  {
    id: "c-behanan",
    name: "Chane Behanan",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "PF",
    jerseyNumber: "21",
    ppg: 9.4,
    rpg: 6.9,
    apg: 0.9,
    spg: 1.1,
    bpg: 0.4,
    rating: 79,
    accolades: "2013 NCAA Champion, 2x NCAA All-Region"
  },
  {
    id: "w-blackshear",
    name: "Wayne Blackshear",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "SG",
    jerseyNumber: "25",
    ppg: 8.3,
    rpg: 3.2,
    apg: 0.8,
    spg: 0.8,
    bpg: 0.4,
    rating: 76,
    accolades: "2013 NCAA Champion, HS Parade AA, 2014-15 NCAA All-Region"
  },
  {
    id: "k-kuric",
    name: "Kyle Kuric",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "SG",
    jerseyNumber: "14",
    ppg: 8.3,
    rpg: 3.2,
    apg: 0.9,
    spg: 1.0,
    bpg: 0.3,
    rating: 80,
    accolades: "2013 NCAA Champion, 2012 All-Big East"
  },
  {
    id: "d-adel",
    name: "Deng Adel",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "SF",
    jerseyNumber: "22",
    ppg: 11.2,
    rpg: 4.1,
    apg: 2.0,
    spg: 0.5,
    bpg: 0.3,
    rating: 78,
    accolades: "2017-18 All-ACC Honorable Mention"
  },
  {
    id: "q-snider",
    name: "Quentin Snider",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "PG",
    jerseyNumber: "4",
    ppg: 9.2,
    rpg: 2.3,
    apg: 3.2,
    spg: 0.5,
    bpg: 0.0,
    rating: 76,
    accolades: "ACC All-Conference Honorable Mention"
  },
  {
    id: "r-spalding",
    name: "Raymond Spalding",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "PF",
    jerseyNumber: "13",
    ppg: 8.1,
    rpg: 6.3,
    apg: 0.9,
    spg: 1.0,
    bpg: 1.1,
    rating: 76,
    accolades: "2018 NBA Draft #56, ACC All-Freshman"
  },
  {
    id: "j-johnson-10",
    name: "Jaylen Johnson",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "PF",
    jerseyNumber: "10",
    ppg: 5.2,
    rpg: 3.8,
    apg: 0.4,
    spg: 0.4,
    bpg: 0.3,
    rating: 73,
    accolades: "ACC Conference"
  },
  {
    id: "m-mathiang",
    name: "Mangok Mathiang",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "C",
    jerseyNumber: "12",
    ppg: 4.8,
    rpg: 4.8,
    apg: 0.5,
    spg: 0.5,
    bpg: 1.3,
    rating: 73,
    accolades: "ACC Conference"
  },
  {
    id: "c-jones-10",
    name: "Chris Jones",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "PG",
    jerseyNumber: "3",
    ppg: 11.5,
    rpg: 2.5,
    apg: 5.5,
    spg: 1.5,
    bpg: 0.2,
    rating: 80,
    accolades: "2015-16 All-ACC (stats from season logs)"
  },
  {
    id: "v-king",
    name: "V.J. King",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "SF",
    jerseyNumber: "0",
    ppg: 7.5,
    rpg: 3.5,
    apg: 0.8,
    spg: 0.7,
    bpg: 0.3,
    rating: 74,
    accolades: "ACC Conference (stats from season logs)"
  },
  {
    id: "r-mcmahon",
    name: "Ryan McMahon",
    era: "modern",
    eraLabel: "The Modern Era",
    position: "SG",
    jerseyNumber: "30",
    ppg: 6.5,
    rpg: 2.5,
    apg: 1.0,
    spg: 0.8,
    bpg: 0.2,
    rating: 73,
    accolades: "ACC Conference (stats from season logs)"
  },
  {
    id: "k-ware",
    name: "Kevin Ware",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "SG",
    jerseyNumber: "5",
    ppg: 5.0,
    rpg: 2.5,
    apg: 1.5,
    spg: 0.9,
    bpg: 0.2,
    rating: 72,
    accolades: "2013 NCAA Champion (stats from season logs)"
  },
  {
    id: "s-van-treese",
    name: "Stephan Van Treese",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "C",
    jerseyNumber: "41",
    ppg: 4.5,
    rpg: 4.5,
    apg: 0.8,
    spg: 0.5,
    bpg: 1.0,
    rating: 71,
    accolades: "ACC Conference (stats from season logs)"
  },
  {
    id: "d-lee-10",
    name: "Damion Lee",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "SG",
    jerseyNumber: "0",
    ppg: 11.0,
    rpg: 3.5,
    apg: 1.5,
    spg: 1.0,
    bpg: 0.2,
    rating: 79,
    accolades: "ACC All-Tournament (stats from season logs)"
  },

  // ── Pitino Era additions ──────────────────────────────────────────────────
  {
    id: "t-rozier",
    name: "Terry Rozier",
    era: "pitino",
    eraLabel: "The Pitino Era",
    position: "SG",
    jerseyNumber: "0",
    ppg: 11.5,
    rpg: 4.9,
    apg: 3.4,
    spg: 1.4,
    bpg: 0.2,
    rating: 88,
    accolades: "2015 All-ACC First Team, 2015 NBA Draft #16 (Celtics), 2023 NBA All-Star"
  },
  {
    id: "c-cunningham",
    name: "Christen Cunningham",
    era: "modern",
    eraLabel: "The Modern Era",
    position: "PG",
    jerseyNumber: "1",
    ppg: 8.2,
    rpg: 3.5,
    apg: 4.8,
    spg: 1.2,
    bpg: 0.1,
    rating: 77,
    accolades: "ACC All-Defensive Team, 2018 All-ACC Honorable Mention"
  },
  {
    id: "d-sutton",
    name: "Dwayne Sutton",
    era: "modern",
    eraLabel: "The Modern Era",
    position: "SF",
    jerseyNumber: "24",
    ppg: 5.8,
    rpg: 5.4,
    apg: 0.9,
    spg: 0.9,
    bpg: 0.3,
    rating: 72,
    accolades: "ACC Conference, 2019 All-ACC Honorable Mention"
  },

  // ── Modern Era additions ──────────────────────────────────────────────────
  {
    id: "j-nwora",
    name: "Jordan Nwora",
    era: "modern",
    eraLabel: "The Modern Era",
    position: "SF",
    jerseyNumber: "33",
    ppg: 14.8,
    rpg: 6.2,
    apg: 1.4,
    spg: 0.6,
    bpg: 0.5,
    rating: 86,
    accolades: "2020 All-ACC First Team, ACC Most Improved Player 2019, 2020 NBA Draft #45 (Bucks)"
  },
  {
    id: "m-williams-5",
    name: "Malik Williams",
    era: "modern",
    eraLabel: "The Modern Era",
    position: "C",
    jerseyNumber: "5",
    ppg: 7.5,
    rpg: 6.5,
    apg: 1.9,
    spg: 0.5,
    bpg: 0.8,
    rating: 75,
    accolades: "ACC All-Conference, 2022 All-ACC Honorable Mention"
  },
  {
    id: "e-ellis",
    name: "El Ellis",
    era: "modern",
    eraLabel: "The Modern Era",
    position: "PG",
    jerseyNumber: "3",
    ppg: 16.2,
    rpg: 3.2,
    apg: 3.8,
    spg: 1.2,
    bpg: 0.2,
    rating: 82,
    accolades: "2022 All-ACC Second Team, ACC scoring leader"
  },
  {
    id: "l-kimble",
    name: "Lamar Kimble",
    era: "modern",
    eraLabel: "The Modern Era",
    position: "SG",
    jerseyNumber: "0",
    ppg: 10.3,
    rpg: 2.8,
    apg: 2.5,
    spg: 0.8,
    bpg: 0.1,
    rating: 73,
    accolades: "ACC Conference, grad transfer from Temple"
  },
  {
    id: "n-locke",
    name: "Noah Locke",
    era: "modern",
    eraLabel: "The Modern Era",
    position: "SG",
    jerseyNumber: "0",
    ppg: 9.2,
    rpg: 2.8,
    apg: 1.8,
    spg: 0.7,
    bpg: 0.1,
    rating: 72,
    accolades: "ACC Conference, grad transfer from Florida"
  },
  {
    id: "j-withers",
    name: "Jae'Lyn Withers",
    era: "modern",
    eraLabel: "The Modern Era",
    position: "PF",
    jerseyNumber: "24",
    ppg: 10.5,
    rpg: 5.2,
    apg: 1.2,
    spg: 0.8,
    bpg: 0.5,
    rating: 74,
    accolades: "ACC Conference, 2022 All-ACC Honorable Mention"
  },
  // ── NEW ADDITIONS ────────────────────────────────────────────────────────

  // ── Modern Era: #0 ───────────────────────────────────────────────────────
  { id:"j-scott", name:"James Scott", era:"modern", eraLabel:"The Modern Era", position:"PF", jerseyNumber:"0", ppg:5.0, rpg:3.5, apg:0.8, spg:0.8, bpg:0.5, rating:62, accolades:"2024-25 season" },
  { id:"m-james-0", name:"Mike James", era:"modern", eraLabel:"The Modern Era", position:"SG", jerseyNumber:"0", ppg:7.5, rpg:2.5, apg:2.0, spg:1.0, bpg:0.2, rating:66, accolades:"2022-24" },
  { id:"d-ree", name:"Devin Ree", era:"modern", eraLabel:"The Modern Era", position:"SG", jerseyNumber:"0", ppg:5.5, rpg:2.0, apg:1.5, spg:0.8, bpg:0.2, rating:63, accolades:"2022-23 season" },
  { id:"a-agau", name:"Akoy Agau", era:"modern", eraLabel:"The Modern Era", position:"C", jerseyNumber:"0", ppg:4.5, rpg:4.0, apg:0.5, spg:0.5, bpg:0.8, rating:63, accolades:"2018-19 (wore #22 '13-15, #44 '15-17, #0 '18-19)" },
  // ── Pitino Era: #0 ───────────────────────────────────────────────────────
  { id:"g-goode", name:"George Goode", era:"pitino", eraLabel:"The Pitino Era", position:"SF", jerseyNumber:"0", ppg:3.0, rpg:2.5, apg:0.5, spg:0.5, bpg:0.3, rating:62, accolades:"2009-11" },
  { id:"s-miller-0", name:"Stuart Miller", era:"pitino", eraLabel:"The Pitino Era", position:"PG", jerseyNumber:"0", ppg:3.5, rpg:1.5, apg:1.5, spg:0.5, bpg:0.1, rating:61, accolades:"2006-08" },
  { id:"j-tinch", name:"Joshua Tinch", era:"pitino", eraLabel:"The Pitino Era", position:"PG", jerseyNumber:"0", ppg:3.0, rpg:1.0, apg:1.5, spg:0.5, bpg:0.1, rating:60, accolades:"2002-04" },
  // ── Crum Era: #00 ────────────────────────────────────────────────────────
  { id:"r-brooks-00", name:"Rashad Brooks", era:"crum", eraLabel:"The Crum Dynasty", position:"PG", jerseyNumber:"00", ppg:7.5, rpg:2.5, apg:3.5, spg:1.0, bpg:0.1, rating:67, accolades:"1999-2001" },
  // ── Modern Era: #1 ───────────────────────────────────────────────────────
  { id:"j-hadley", name:"J'Vonne Hadley", era:"modern", eraLabel:"The Modern Era", position:"SF", jerseyNumber:"1", ppg:8.0, rpg:3.0, apg:1.5, spg:1.0, bpg:0.3, rating:66, accolades:"2024-25 season" },
  { id:"c-williams-1", name:"Curtis Williams", era:"modern", eraLabel:"The Modern Era", position:"SF", jerseyNumber:"1", ppg:6.0, rpg:3.5, apg:1.0, spg:0.8, bpg:0.3, rating:64, accolades:"2023-24 season" },
  { id:"c-jones", name:"Carlik Jones", era:"modern", eraLabel:"The Modern Era", position:"PG", jerseyNumber:"1", ppg:18.6, rpg:4.5, apg:4.5, spg:1.7, bpg:0.2, rating:90, accolades:"2021 ACC Player of the Year; Louisville's all-time assists leader" },
  { id:"k-oddo", name:"Keith Oddo", era:"modern", eraLabel:"The Modern Era", position:"PG", jerseyNumber:"1", ppg:5.0, rpg:2.0, apg:2.5, spg:0.8, bpg:0.1, rating:62, accolades:"2019-20 season" },
  // ── Pitino Era: #1 ───────────────────────────────────────────────────────
  { id:"l-thomas-1", name:"Lance Thomas", era:"pitino", eraLabel:"The Pitino Era", position:"SF", jerseyNumber:"1", ppg:4.5, rpg:3.5, apg:0.8, spg:0.8, bpg:0.3, rating:63, accolades:"2017-18 season" },
  { id:"t-hicks", name:"Tony Hicks", era:"pitino", eraLabel:"The Pitino Era", position:"PG", jerseyNumber:"1", ppg:3.5, rpg:1.5, apg:1.5, spg:0.5, bpg:0.1, rating:62, accolades:"2016-17 season" },
  { id:"a-gill", name:"Anton Gill", era:"pitino", eraLabel:"The Pitino Era", position:"SG", jerseyNumber:"1", ppg:4.0, rpg:1.5, apg:1.0, spg:0.5, bpg:0.1, rating:62, accolades:"2013-15" },
  { id:"a-nunez", name:"Angel Nunez", era:"pitino", eraLabel:"The Pitino Era", position:"PG", jerseyNumber:"1", ppg:3.5, rpg:1.5, apg:1.5, spg:0.5, bpg:0.1, rating:61, accolades:"2011-12 season" },
  { id:"k-dartez", name:"Kendall Dartez", era:"pitino", eraLabel:"The Pitino Era", position:"PG", jerseyNumber:"1", ppg:3.0, rpg:1.0, apg:1.5, spg:0.5, bpg:0.1, rating:61, accolades:"2002-04" },
  // ── Crum Era: #1 ─────────────────────────────────────────────────────────
  { id:"m-wilkinson", name:"Mac Wilkinson", era:"crum", eraLabel:"The Crum Dynasty", position:"SG", jerseyNumber:"1", ppg:3.5, rpg:2.0, apg:0.8, spg:0.5, bpg:0.1, rating:62, accolades:"2000-01 season" },
  // ── Modern Era: #2 ───────────────────────────────────────────────────────
  { id:"d-perry", name:"Darius Perry", era:"modern", eraLabel:"The Modern Era", position:"PG", jerseyNumber:"2", ppg:7.5, rpg:2.5, apg:3.0, spg:1.2, bpg:0.2, rating:68, accolades:"2017-20" },
  // ── Modern Era: #3 ───────────────────────────────────────────────────────
  { id:"k-johnson-3", name:"Koren Johnson", era:"modern", eraLabel:"The Modern Era", position:"PG", jerseyNumber:"3", ppg:7.5, rpg:2.5, apg:2.0, spg:1.0, bpg:0.2, rating:65, accolades:"2024-25 season" },
  { id:"h-orbaugh", name:"Hogan Orbaugh", era:"modern", eraLabel:"The Modern Era", position:"SF", jerseyNumber:"3", ppg:3.5, rpg:2.5, apg:0.5, spg:0.5, bpg:0.2, rating:61, accolades:"2020-21 (wore #12 '19-20, #3 '20-21)" },
  { id:"j-griffin-3", name:"Jo Griffin", era:"modern", eraLabel:"The Modern Era", position:"SF", jerseyNumber:"3", ppg:4.0, rpg:2.0, apg:0.8, spg:0.5, bpg:0.2, rating:62, accolades:"2017-19" },
  // ── Pitino Era: #3 ───────────────────────────────────────────────────────
  { id:"t-lewis", name:"Trey Lewis", era:"pitino", eraLabel:"The Pitino Era", position:"PG", jerseyNumber:"3", ppg:14.5, rpg:3.5, apg:3.5, spg:1.2, bpg:0.2, rating:74, accolades:"2015-16 (transfer from Cleveland State; C-USA scoring leader)" },
  { id:"b-northern", name:"Bryant Northern", era:"pitino", eraLabel:"The Pitino Era", position:"SF", jerseyNumber:"3", ppg:3.5, rpg:2.5, apg:0.5, spg:0.5, bpg:0.2, rating:62, accolades:"2000-03" },
  // ── Crum Era: #3 ─────────────────────────────────────────────────────────
  { id:"k-williams-3", name:"Keith Williams", era:"crum", eraLabel:"The Crum Dynasty", position:"SF", jerseyNumber:"3", ppg:5.0, rpg:3.5, apg:0.8, spg:0.8, bpg:0.3, rating:64, accolades:"1985-90" },
  // ── Hickman Era: #3 ──────────────────────────────────────────────────────
  { id:"c-cox-3", name:"Corky Cox", era:"hickman", eraLabel:"The Hickman Era", position:"PG", jerseyNumber:"3", ppg:5.0, rpg:2.5, apg:1.5, spg:0.0, bpg:0.0, rating:62, accolades:"1953-54 (stats from season logs)" },
  // ── Modern Era: #4 ───────────────────────────────────────────────────────
  { id:"c-sherman", name:"Cole Sherman", era:"modern", eraLabel:"The Modern Era", position:"PF", jerseyNumber:"4", ppg:4.0, rpg:3.0, apg:0.5, spg:0.5, bpg:0.5, rating:61, accolades:"2024-25 season" },
  { id:"t-johnson-4", name:"Ty-Laur Johnson", era:"modern", eraLabel:"The Modern Era", position:"PG", jerseyNumber:"4", ppg:8.5, rpg:2.0, apg:3.5, spg:1.2, bpg:0.2, rating:69, accolades:"2023-24 season" },
  { id:"r-wheeler", name:"Roosevelt Wheeler", era:"modern", eraLabel:"The Modern Era", position:"C", jerseyNumber:"4", ppg:6.5, rpg:5.5, apg:0.5, spg:0.5, bpg:1.0, rating:66, accolades:"2021-23" },
  { id:"b-colbert", name:"Brad Colbert", era:"modern", eraLabel:"The Modern Era", position:"SG", jerseyNumber:"4", ppg:4.0, rpg:2.0, apg:1.0, spg:0.8, bpg:0.2, rating:62, accolades:"2020-21 season" },
  { id:"g-williams-4", name:"Grant Williams", era:"modern", eraLabel:"The Modern Era", position:"SF", jerseyNumber:"4", ppg:5.5, rpg:3.5, apg:1.0, spg:0.8, bpg:0.3, rating:64, accolades:"2019-20 season" },
  { id:"k-fore", name:"Khwan Fore", era:"modern", eraLabel:"The Modern Era", position:"PG", jerseyNumber:"4", ppg:4.5, rpg:2.0, apg:2.5, spg:0.8, bpg:0.1, rating:63, accolades:"2018-19 season" },
  // ── Pitino Era: #4 ───────────────────────────────────────────────────────
  { id:"d-avare", name:"Dillon Avare", era:"pitino", eraLabel:"The Pitino Era", position:"PF", jerseyNumber:"4", ppg:4.0, rpg:3.5, apg:0.5, spg:0.5, bpg:0.5, rating:62, accolades:"2014-16" },
  { id:"r-buckles", name:"Rakeem Buckles", era:"pitino", eraLabel:"The Pitino Era", position:"PF", jerseyNumber:"4", ppg:5.5, rpg:5.0, apg:0.8, spg:0.8, bpg:0.5, rating:65, accolades:"2009-12" },
  { id:"n-diakite", name:"Nouha Diakite", era:"pitino", eraLabel:"The Pitino Era", position:"C", jerseyNumber:"4", ppg:3.0, rpg:3.0, apg:0.3, spg:0.3, bpg:0.5, rating:61, accolades:"2003-04 season" },
  { id:"h-turner-4", name:"Hajj Turner", era:"pitino", eraLabel:"The Pitino Era", position:"PF", jerseyNumber:"4", ppg:5.5, rpg:4.5, apg:0.5, spg:0.8, bpg:0.5, rating:65, accolades:"1998-2002 (wore #13 '97-98)" },
  // ── Crum Era: #4 ─────────────────────────────────────────────────────────
  { id:"j-johnson-4c", name:"Jerry Johnson", era:"crum", eraLabel:"The Crum Dynasty", position:"PG", jerseyNumber:"4", ppg:4.0, rpg:1.5, apg:2.5, spg:0.8, bpg:0.1, rating:63, accolades:"1996-98" },
  { id:"t-rogers", name:"Tick Rogers", era:"crum", eraLabel:"The Crum Dynasty", position:"SF", jerseyNumber:"4", ppg:5.0, rpg:3.5, apg:0.8, spg:0.8, bpg:0.3, rating:64, accolades:"1992-96" },
  { id:"d-webb", name:"Derwin Webb", era:"crum", eraLabel:"The Crum Dynasty", position:"PG", jerseyNumber:"4", ppg:3.0, rpg:1.5, apg:2.0, spg:0.5, bpg:0.1, rating:61, accolades:"1988-89 season" },
  // ── Hickman Era: #4 ──────────────────────────────────────────────────────
  { id:"r-shackelford", name:"Roscoe Shackelford", era:"hickman", eraLabel:"The Hickman Era", position:"C", jerseyNumber:"4", ppg:6.0, rpg:5.5, apg:0.5, spg:0.0, bpg:0.0, rating:63, accolades:"1954-55 (stats from season logs)" },
  { id:"h-harrah", name:"Herb Harrah", era:"hickman", eraLabel:"The Hickman Era", position:"PG", jerseyNumber:"4", ppg:7.0, rpg:4.5, apg:1.0, spg:0.0, bpg:0.0, rating:64, accolades:"1953-55 (wore #4 and #6)" },
  // ── Modern Era: #5 ───────────────────────────────────────────────────────
  { id:"b-huntley", name:"Brandon Huntley-Hatfield", era:"modern", eraLabel:"The Modern Era", position:"PF", jerseyNumber:"5", ppg:7.5, rpg:5.5, apg:0.8, spg:0.8, bpg:0.8, rating:68, accolades:"2022-24 (transfer from Tennessee)" },
  // ── Pitino Era: #5 ───────────────────────────────────────────────────────
  { id:"m-stockman", name:"Matz Stockman", era:"pitino", eraLabel:"The Pitino Era", position:"C", jerseyNumber:"5", ppg:4.5, rpg:4.5, apg:0.3, spg:0.3, bpg:1.2, rating:64, accolades:"2014-17" },
  { id:"c-smith-5", name:"Chris Smith", era:"pitino", eraLabel:"The Pitino Era", position:"SG", jerseyNumber:"5", ppg:5.5, rpg:2.5, apg:2.0, spg:0.8, bpg:0.2, rating:65, accolades:"2010-12" },
  { id:"b-bender", name:"Brandon Bender", era:"pitino", eraLabel:"The Pitino Era", position:"PG", jerseyNumber:"5", ppg:3.0, rpg:1.5, apg:2.0, spg:0.5, bpg:0.1, rating:61, accolades:"2001-02 season" },
  // ── Crum Era: #5 ─────────────────────────────────────────────────────────
  { id:"m-case", name:"Mike Case", era:"crum", eraLabel:"The Crum Dynasty", position:"SG", jerseyNumber:"5", ppg:5.5, rpg:2.5, apg:1.0, spg:0.8, bpg:0.2, rating:65, accolades:"1988-93" },
  // ── Hickman Era: #5 ──────────────────────────────────────────────────────
  { id:"j-moreman", name:"Jerry Moreman", era:"hickman", eraLabel:"The Hickman Era", position:"C", jerseyNumber:"5", ppg:5.5, rpg:5.0, apg:0.5, spg:0.0, bpg:0.0, rating:62, accolades:"1953-55 (stats from season logs)" },
  // ── Modern Era: #6 ───────────────────────────────────────────────────────
  { id:"r-smith-6", name:"Reyne Smith", era:"modern", eraLabel:"The Modern Era", position:"SG", jerseyNumber:"6", ppg:6.5, rpg:2.0, apg:1.5, spg:0.8, bpg:0.2, rating:65, accolades:"2024-25 season" },
  // ── Hickman Era: #7 ──────────────────────────────────────────────────────
  { id:"k-pryor", name:"Kasean Pryor", era:"modern", eraLabel:"The Modern Era", position:"SF", jerseyNumber:"7", ppg:5.0, rpg:3.0, apg:0.8, spg:0.8, bpg:0.3, rating:63, accolades:"2024-25 season" },
  { id:"d-keffer", name:"Dick Keffer", era:"hickman", eraLabel:"The Hickman Era", position:"PG", jerseyNumber:"7", ppg:6.0, rpg:3.0, apg:1.5, spg:0.0, bpg:0.0, rating:63, accolades:"1953-55 (stats from season logs)" },
  // ── Modern Era: #9 ───────────────────────────────────────────────────────
  { id:"k-rooths", name:"Khani Rooths", era:"modern", eraLabel:"The Modern Era", position:"SG", jerseyNumber:"9", ppg:5.5, rpg:2.0, apg:1.5, spg:0.8, bpg:0.2, rating:63, accolades:"2024-25 season" },
  // ── Modern Era: #10 ──────────────────────────────────────────────────────
  { id:"k-glenn", name:"Kaleb Glenn", era:"modern", eraLabel:"The Modern Era", position:"SG", jerseyNumber:"10", ppg:6.5, rpg:2.5, apg:1.5, spg:0.8, bpg:0.2, rating:65, accolades:"2023-24 season" },
  { id:"s-williamson", name:"Samuell Williamson", era:"modern", eraLabel:"The Modern Era", position:"SF", jerseyNumber:"10", ppg:12.0, rpg:5.5, apg:1.5, spg:1.5, bpg:0.5, rating:77, accolades:"2019-22; 2022 All-ACC honorable mention" },
  { id:"w-battaile", name:"Wyatt Battaile", era:"modern", eraLabel:"The Modern Era", position:"PG", jerseyNumber:"10", ppg:4.0, rpg:1.5, apg:2.0, spg:0.5, bpg:0.1, rating:62, accolades:"2018-19 season" },
  // ── Pitino Era: #10 ──────────────────────────────────────────────────────
  { id:"p-davis-10", name:"Prileu Davis", era:"pitino", eraLabel:"The Pitino Era", position:"PG", jerseyNumber:"10", ppg:4.0, rpg:1.5, apg:2.0, spg:0.5, bpg:0.1, rating:62, accolades:"2002-03 season" },
  // ── Crum Era: #10 ────────────────────────────────────────────────────────
  { id:"s-fraley", name:"Shannon Fraley", era:"crum", eraLabel:"The Crum Dynasty", position:"PG", jerseyNumber:"10", ppg:5.0, rpg:2.0, apg:2.5, spg:0.8, bpg:0.1, rating:64, accolades:"1987-91 (wore #15 '87-89, #10 '89-91)" },
  { id:"m-mcswain", name:"Mark McSwain", era:"crum", eraLabel:"The Crum Dynasty", position:"PF", jerseyNumber:"10", ppg:5.5, rpg:5.0, apg:0.5, spg:0.8, bpg:0.5, rating:65, accolades:"1984-87" },
  // ── Hickman Era: #10 ─────────────────────────────────────────────────────
  { id:"l-holman", name:"Larry Holman", era:"hickman", eraLabel:"The Hickman Era", position:"PF", jerseyNumber:"10", ppg:7.5, rpg:5.5, apg:0.8, spg:0.0, bpg:0.0, rating:65, accolades:"1964-65 (stats from season logs)" },
  { id:"b-akridge", name:"Bill Akridge", era:"hickman", eraLabel:"The Hickman Era", position:"SG", jerseyNumber:"10", ppg:6.5, rpg:3.5, apg:1.5, spg:0.0, bpg:0.0, rating:64, accolades:"1962-64 (stats from season logs)" },
  { id:"g-burnette", name:"George Burnette", era:"hickman", eraLabel:"The Hickman Era", position:"PF", jerseyNumber:"10", ppg:6.0, rpg:5.5, apg:0.5, spg:0.0, bpg:0.0, rating:63, accolades:"1958-59 (stats from season logs)" },
  { id:"g-dupont", name:"Gerald DuPont", era:"hickman", eraLabel:"The Hickman Era", position:"C", jerseyNumber:"10", ppg:5.5, rpg:5.5, apg:0.3, spg:0.0, bpg:0.0, rating:62, accolades:"1957-58 (stats from season logs)" },
  { id:"j-heins", name:"James Heins", era:"hickman", eraLabel:"The Hickman Era", position:"C", jerseyNumber:"10", ppg:5.0, rpg:4.5, apg:0.3, spg:0.0, bpg:0.0, rating:61, accolades:"1954-55 (stats from season logs)" },
  // ── Modern Era: #11 ──────────────────────────────────────────────────────
  { id:"k-rodgers", name:"Kobe Rodgers", era:"modern", eraLabel:"The Modern Era", position:"SF", jerseyNumber:"11", ppg:5.5, rpg:3.0, apg:1.0, spg:0.8, bpg:0.3, rating:63, accolades:"2024-25 season" },
  { id:"d-evans", name:"Dennis Evans", era:"modern", eraLabel:"The Modern Era", position:"PF", jerseyNumber:"11", ppg:5.0, rpg:4.5, apg:0.5, spg:0.5, bpg:0.8, rating:63, accolades:"2023-24 season" },
  { id:"f-basili", name:"Fabio Basili", era:"modern", eraLabel:"The Modern Era", position:"PF", jerseyNumber:"11", ppg:4.5, rpg:4.0, apg:0.8, spg:0.5, bpg:0.5, rating:62, accolades:"2022-23 season" },
  { id:"m-faulkner", name:"Mason Faulkner", era:"modern", eraLabel:"The Modern Era", position:"PG", jerseyNumber:"11", ppg:9.5, rpg:2.5, apg:3.5, spg:1.0, bpg:0.2, rating:69, accolades:"2021-22 (transfer from Western Carolina)" },
  { id:"q-slazinski", name:"Quinn Slazinski", era:"modern", eraLabel:"The Modern Era", position:"SF", jerseyNumber:"11", ppg:6.5, rpg:4.0, apg:1.0, spg:0.8, bpg:0.3, rating:65, accolades:"2019-21" },
  // ── Pitino Era: #11 ──────────────────────────────────────────────────────
  { id:"j-henderson-11", name:"Jay Henderson", era:"pitino", eraLabel:"The Pitino Era", position:"PG", jerseyNumber:"11", ppg:5.0, rpg:2.0, apg:2.5, spg:0.8, bpg:0.1, rating:63, accolades:"2015-17" },
  { id:"c-brickley", name:"Chris Brickley", era:"pitino", eraLabel:"The Pitino Era", position:"SF", jerseyNumber:"11", ppg:4.0, rpg:2.5, apg:0.8, spg:0.5, bpg:0.2, rating:62, accolades:"2009-10 season" },
  // ── Crum Era: #11 ────────────────────────────────────────────────────────
  { id:"c-taylor-11", name:"Charlie Taylor", era:"crum", eraLabel:"The Crum Dynasty", position:"PG", jerseyNumber:"11", ppg:4.5, rpg:1.5, apg:2.0, spg:0.8, bpg:0.1, rating:63, accolades:"1995-96 season" },
  { id:"j-brewer", name:"James Brewer", era:"crum", eraLabel:"The Crum Dynasty", position:"PF", jerseyNumber:"11", ppg:5.5, rpg:5.0, apg:0.5, spg:0.8, bpg:0.5, rating:65, accolades:"1988-93" },
  // ── Modern Era: #12 ──────────────────────────────────────────────────────
  { id:"p-antonelli", name:"Patrick Antonelli", era:"modern", eraLabel:"The Modern Era", position:"PG", jerseyNumber:"12", ppg:5.5, rpg:2.0, apg:2.0, spg:0.8, bpg:0.1, rating:63, accolades:"2024-25 season" },
  { id:"j-traynor", name:"JJ Traynor", era:"modern", eraLabel:"The Modern Era", position:"PF", jerseyNumber:"12", ppg:5.5, rpg:5.0, apg:0.8, spg:0.5, bpg:0.5, rating:64, accolades:"2020-24" },
  { id:"j-redding", name:"Jacob Redding", era:"modern", eraLabel:"The Modern Era", position:"SG", jerseyNumber:"12", ppg:4.5, rpg:2.5, apg:1.0, spg:0.5, bpg:0.2, rating:62, accolades:"2017-19 (wore #12)" },
  // ── Pitino Era: #12 ──────────────────────────────────────────────────────
  { id:"z-price", name:"Zach Price", era:"pitino", eraLabel:"The Pitino Era", position:"PF", jerseyNumber:"12", ppg:4.0, rpg:3.5, apg:0.5, spg:0.5, bpg:0.5, rating:62, accolades:"2011-12 season" },
  { id:"r-delk", name:"Reginald Delk", era:"pitino", eraLabel:"The Pitino Era", position:"PG", jerseyNumber:"12", ppg:4.5, rpg:2.0, apg:2.0, spg:0.8, bpg:0.1, rating:63, accolades:"2008-10" },
  { id:"b-gianiny", name:"Brad Gianiny", era:"pitino", eraLabel:"The Pitino Era", position:"SG", jerseyNumber:"12", ppg:4.5, rpg:2.0, apg:1.0, spg:0.5, bpg:0.1, rating:63, accolades:"2003-07" },
  { id:"c-hurt", name:"Carlos Hurt", era:"pitino", eraLabel:"The Pitino Era", position:"PF", jerseyNumber:"12", ppg:4.0, rpg:3.5, apg:0.5, spg:0.5, bpg:0.5, rating:62, accolades:"2001-02 season" },
  // ── Crum Era: #12 ────────────────────────────────────────────────────────
  { id:"m-akridge", name:"Matt Akridge", era:"crum", eraLabel:"The Crum Dynasty", position:"SG", jerseyNumber:"12", ppg:4.5, rpg:2.0, apg:1.0, spg:0.8, bpg:0.1, rating:63, accolades:"1995-98" },
  { id:"d-calhoun", name:"Doug Calhoun", era:"crum", eraLabel:"The Crum Dynasty", position:"PG", jerseyNumber:"12", ppg:4.5, rpg:2.0, apg:2.5, spg:0.8, bpg:0.1, rating:63, accolades:"1992-94" },
  { id:"c-hawley", name:"Craig Hawley", era:"crum", eraLabel:"The Crum Dynasty", position:"SG", jerseyNumber:"12", ppg:5.0, rpg:2.5, apg:1.0, spg:0.8, bpg:0.2, rating:64, accolades:"1986-90" },
  { id:"k-jones-12", name:"Kent Jones", era:"crum", eraLabel:"The Crum Dynasty", position:"SG", jerseyNumber:"12", ppg:5.5, rpg:2.5, apg:1.5, spg:0.8, bpg:0.2, rating:65, accolades:"1981-85" },
  // ── Modern Era: #13 ──────────────────────────────────────────────────────
  { id:"f-anselem", name:"Frank Anselem-Ibe", era:"modern", eraLabel:"The Modern Era", position:"C", jerseyNumber:"13", ppg:5.5, rpg:4.5, apg:0.5, spg:0.5, bpg:1.2, rating:64, accolades:"2024-25 season" },
  { id:"d-jovanovich", name:"Danilo Jovanovich", era:"modern", eraLabel:"The Modern Era", position:"PF", jerseyNumber:"13", ppg:5.0, rpg:4.0, apg:1.0, spg:0.5, bpg:0.5, rating:63, accolades:"2023-24 season" },
  { id:"j-west", name:"Jarrod West", era:"modern", eraLabel:"The Modern Era", position:"PG", jerseyNumber:"13", ppg:8.5, rpg:2.5, apg:4.5, spg:1.2, bpg:0.2, rating:69, accolades:"2021-22 (transfer from Marshall)" },
  { id:"d-johnson-13", name:"David Johnson", era:"modern", eraLabel:"The Modern Era", position:"PG", jerseyNumber:"13", ppg:10.0, rpg:4.0, apg:4.0, spg:1.5, bpg:0.3, rating:74, accolades:"2019-21; 2021 All-ACC Freshman team" },
  // ── Pitino Era: #13 ──────────────────────────────────────────────────────
  { id:"m-jackson-13", name:"Mark Jackson", era:"pitino", eraLabel:"The Pitino Era", position:"PF", jerseyNumber:"13", ppg:4.5, rpg:4.0, apg:0.5, spg:0.5, bpg:0.5, rating:62, accolades:"2011-12 season" },
  { id:"a-mohammed", name:"Alhaji Mohammed", era:"pitino", eraLabel:"The Pitino Era", position:"C", jerseyNumber:"13", ppg:5.5, rpg:4.5, apg:0.5, spg:0.5, bpg:1.2, rating:64, accolades:"2001-04" },
  // ── Crum Era: #13 ────────────────────────────────────────────────────────
  { id:"q-bailey", name:"Quintin Bailey", era:"crum", eraLabel:"The Crum Dynasty", position:"SG", jerseyNumber:"13", ppg:5.0, rpg:2.0, apg:1.5, spg:0.8, bpg:0.2, rating:64, accolades:"1998-2000" },
  { id:"m-carroll-13", name:"Mike Carroll", era:"crum", eraLabel:"The Crum Dynasty", position:"SG", jerseyNumber:"13", ppg:5.0, rpg:2.5, apg:1.5, spg:0.0, bpg:0.0, rating:63, accolades:"1973-74 (stats from season logs)" },
  { id:"r-shay", name:"Richard Shay", era:"crum", eraLabel:"The Crum Dynasty", position:"PF", jerseyNumber:"13", ppg:4.0, rpg:4.0, apg:0.5, spg:0.0, bpg:0.0, rating:62, accolades:"1972-73 (stats from season logs)" },
  { id:"b-murton", name:"Bill Murton", era:"crum", eraLabel:"The Crum Dynasty", position:"C", jerseyNumber:"13", ppg:3.5, rpg:3.5, apg:0.3, spg:0.0, bpg:0.0, rating:61, accolades:"1971-72 (stats from season logs)" },
  // ── Modern Era: #14 ──────────────────────────────────────────────────────
  { id:"d-davis-14", name:"Dre Davis", era:"modern", eraLabel:"The Modern Era", position:"SF", jerseyNumber:"14", ppg:8.5, rpg:4.5, apg:1.5, spg:1.2, bpg:0.3, rating:70, accolades:"2020-22; ACC honorable mention" },
  // ── Pitino Era: #14 ──────────────────────────────────────────────────────
  { id:"a-mahmoud", name:"Anas Mahmoud", era:"pitino", eraLabel:"The Pitino Era", position:"C", jerseyNumber:"14", ppg:5.0, rpg:4.5, apg:0.3, spg:0.3, bpg:2.5, rating:69, accolades:"2014-18; shot-blocking specialist" },
  { id:"l-baumann", name:"Logan Baumann", era:"pitino", eraLabel:"The Pitino Era", position:"PF", jerseyNumber:"14", ppg:4.0, rpg:3.5, apg:0.5, spg:0.5, bpg:0.5, rating:62, accolades:"2012-13 season" },
  // ── Crum Era: #14 ────────────────────────────────────────────────────────
  { id:"d-smith-14", name:"David Smith", era:"crum", eraLabel:"The Crum Dynasty", position:"SF", jerseyNumber:"14", ppg:5.5, rpg:3.5, apg:1.0, spg:0.0, bpg:0.0, rating:64, accolades:"1974-78 (stats from season logs)" },
  // ── Hickman Era: #14 ─────────────────────────────────────────────────────
  { id:"j-frazier-14", name:"Jadie Frazier", era:"hickman", eraLabel:"The Hickman Era", position:"PF", jerseyNumber:"14", ppg:7.0, rpg:5.5, apg:0.8, spg:0.0, bpg:0.0, rating:65, accolades:"1960-63 (stats from season logs)" },
  { id:"h-andrews", name:"Harold Andrews", era:"hickman", eraLabel:"The Hickman Era", position:"PF", jerseyNumber:"14", ppg:6.5, rpg:5.5, apg:0.5, spg:0.0, bpg:0.0, rating:64, accolades:"1956-59 (stats from season logs)" },
  { id:"h-pike", name:"Harold Pike", era:"hickman", eraLabel:"The Hickman Era", position:"PF", jerseyNumber:"14", ppg:6.5, rpg:5.5, apg:0.5, spg:0.0, bpg:0.0, rating:64, accolades:"1955-57 (stats from season logs)" },
  { id:"w-powell", name:"William Powell", era:"hickman", eraLabel:"The Hickman Era", position:"C", jerseyNumber:"14", ppg:6.5, rpg:6.0, apg:0.3, spg:0.0, bpg:0.0, rating:64, accolades:"1950-54 (stats from season logs)" },
  // ── Modern Era: #15 ──────────────────────────────────────────────────────
  { id:"a-khalifa", name:"Aly Khalifa", era:"modern", eraLabel:"The Modern Era", position:"C", jerseyNumber:"15", ppg:5.0, rpg:4.5, apg:0.5, spg:0.5, bpg:1.0, rating:63, accolades:"2024-25 season" },
  { id:"h-miller-15", name:"Hercy Miller", era:"modern", eraLabel:"The Modern Era", position:"SG", jerseyNumber:"15", ppg:7.0, rpg:2.5, apg:1.5, spg:0.8, bpg:0.2, rating:66, accolades:"2022-24" },
  { id:"d-schultz", name:"Drew Schultz", era:"modern", eraLabel:"The Modern Era", position:"PG", jerseyNumber:"15", ppg:4.5, rpg:2.0, apg:2.5, spg:0.5, bpg:0.1, rating:62, accolades:"2020-22" },
  // ── Pitino Era: #15 ──────────────────────────────────────────────────────
  { id:"t-sharpe", name:"Tyler Sharpe", era:"pitino", eraLabel:"The Pitino Era", position:"SG", jerseyNumber:"15", ppg:5.0, rpg:2.0, apg:1.5, spg:0.5, bpg:0.1, rating:63, accolades:"2016-17 season" },
  { id:"t-gilbert", name:"Trent Gilbert", era:"pitino", eraLabel:"The Pitino Era", position:"SG", jerseyNumber:"15", ppg:3.5, rpg:1.5, apg:1.0, spg:0.5, bpg:0.1, rating:62, accolades:"2014-15 season" },
  { id:"t-henderson-15", name:"Tim Henderson", era:"pitino", eraLabel:"The Pitino Era", position:"PG", jerseyNumber:"15", ppg:4.5, rpg:1.5, apg:2.5, spg:0.5, bpg:0.1, rating:63, accolades:"2010-14" },
  { id:"s-naydenov", name:"Simeon Naydenov", era:"pitino", eraLabel:"The Pitino Era", position:"C", jerseyNumber:"15", ppg:3.5, rpg:3.0, apg:0.3, spg:0.3, bpg:0.5, rating:61, accolades:"2000-03" },
  // ── Crum Era: #15 ────────────────────────────────────────────────────────
  { id:"t-best", name:"Travis Best", era:"crum", eraLabel:"The Crum Dynasty", position:"PG", jerseyNumber:"15", ppg:9.5, rpg:3.0, apg:5.5, spg:1.5, bpg:0.1, rating:73, accolades:"1997-99 (Louisville career)" },
  { id:"m-layston", name:"Micah Layston", era:"crum", eraLabel:"The Crum Dynasty", position:"SG", jerseyNumber:"15", ppg:4.0, rpg:2.0, apg:1.0, spg:0.5, bpg:0.1, rating:62, accolades:"1995-96 season" },
  { id:"t-howard-15", name:"Todd Howard", era:"crum", eraLabel:"The Crum Dynasty", position:"SF", jerseyNumber:"15", ppg:5.5, rpg:4.0, apg:0.8, spg:0.8, bpg:0.3, rating:65, accolades:"1989-91" },
  { id:"k-walls", name:"Kevin Walls", era:"crum", eraLabel:"The Crum Dynasty", position:"PF", jerseyNumber:"15", ppg:5.5, rpg:5.5, apg:0.5, spg:0.5, bpg:0.5, rating:65, accolades:"1984-87" },
  { id:"g-deuser", name:"Greg Deuser", era:"crum", eraLabel:"The Crum Dynasty", position:"PF", jerseyNumber:"15", ppg:5.5, rpg:5.0, apg:0.8, spg:0.0, bpg:0.0, rating:65, accolades:"1977-82 (stats from season logs)" },
  { id:"w-cosby", name:"Wayne Cosby", era:"crum", eraLabel:"The Crum Dynasty", position:"SF", jerseyNumber:"15", ppg:5.0, rpg:3.5, apg:0.8, spg:0.0, bpg:0.0, rating:64, accolades:"1974-76 (stats from season logs)" },
  { id:"b-butler-15", name:"Bill Butler", era:"crum", eraLabel:"The Crum Dynasty", position:"SF", jerseyNumber:"15", ppg:5.5, rpg:4.0, apg:1.0, spg:0.0, bpg:0.0, rating:65, accolades:"1972-74 (stats from season logs)" },
  // ── Hickman Era: #15 ─────────────────────────────────────────────────────
  { id:"b-windchy", name:"Bill Windchy", era:"hickman", eraLabel:"The Hickman Era", position:"SG", jerseyNumber:"15", ppg:7.0, rpg:3.0, apg:1.5, spg:0.0, bpg:0.0, rating:65, accolades:"1964-65 (stats from season logs)" },
  { id:"s-smith-15", name:"Sam Smith", era:"hickman", eraLabel:"The Hickman Era", position:"PG", jerseyNumber:"15", ppg:6.5, rpg:2.5, apg:2.0, spg:0.0, bpg:0.0, rating:64, accolades:"1963-64 (stats from season logs)" },
  { id:"j-stripling", name:"Jon Stripling", era:"hickman", eraLabel:"The Hickman Era", position:"PG", jerseyNumber:"15", ppg:6.0, rpg:2.5, apg:2.5, spg:0.0, bpg:0.0, rating:64, accolades:"1960-63 (stats from season logs)" },
  { id:"h-andrews-15", name:"Harley Andrews", era:"hickman", eraLabel:"The Hickman Era", position:"PF", jerseyNumber:"15", ppg:6.5, rpg:5.5, apg:0.5, spg:0.0, bpg:0.0, rating:64, accolades:"1958-60 (stats from season logs)" },
  { id:"j-heeren", name:"Jim Heeren", era:"hickman", eraLabel:"The Hickman Era", position:"PF", jerseyNumber:"15", ppg:6.0, rpg:5.0, apg:0.5, spg:0.0, bpg:0.0, rating:63, accolades:"1957-59 (stats from season logs)" },
  { id:"j-prudhoe", name:"John Prudhoe", era:"hickman", eraLabel:"The Hickman Era", position:"C", jerseyNumber:"15", ppg:6.5, rpg:6.0, apg:0.3, spg:0.0, bpg:0.0, rating:64, accolades:"1951-55 (stats from season logs)" },
  // ── Modern Era: #20 ──────────────────────────────────────────────────────
  { id:"j-nickelberry", name:"Josh Nickelberry", era:"modern", eraLabel:"The Modern Era", position:"SG", jerseyNumber:"20", ppg:6.5, rpg:2.5, apg:1.5, spg:1.0, bpg:0.2, rating:66, accolades:"2019-21" },
  { id:"s-bearden", name:"Sam Bearden", era:"modern", eraLabel:"The Modern Era", position:"PF", jerseyNumber:"20", ppg:5.0, rpg:4.0, apg:0.5, spg:0.5, bpg:0.5, rating:63, accolades:"2020-22 (wore #2 '20-21, #20 '21-22)" },
  // ── Pitino Era: #20 ──────────────────────────────────────────────────────
  { id:"w-scott-20", name:"Will Scott", era:"pitino", eraLabel:"The Pitino Era", position:"SG", jerseyNumber:"20", ppg:4.0, rpg:2.0, apg:1.5, spg:0.5, bpg:0.1, rating:62, accolades:"2006-08" },
  // ── Crum Era: #20 ────────────────────────────────────────────────────────
  { id:"j-king-20", name:"Jimmy King", era:"crum", eraLabel:"The Crum Dynasty", position:"PG", jerseyNumber:"20", ppg:6.0, rpg:2.5, apg:3.5, spg:1.0, bpg:0.1, rating:66, accolades:"1992-96" },
  { id:"k-stone", name:"Kip Stone", era:"crum", eraLabel:"The Crum Dynasty", position:"PG", jerseyNumber:"20", ppg:5.0, rpg:2.5, apg:2.5, spg:0.8, bpg:0.1, rating:64, accolades:"1990-92" },
  { id:"p-yaden", name:"Paul Yaden", era:"crum", eraLabel:"The Crum Dynasty", position:"SG", jerseyNumber:"20", ppg:4.0, rpg:2.0, apg:1.0, spg:0.5, bpg:0.1, rating:62, accolades:"1996-98" },
  { id:"t-kennebrew", name:"Titus Kennebrew", era:"crum", eraLabel:"The Crum Dynasty", position:"SG", jerseyNumber:"20", ppg:4.0, rpg:2.0, apg:1.5, spg:0.5, bpg:0.1, rating:62, accolades:"1998-99 season" },
  { id:"l-loehle", name:"Larry Loehle", era:"crum", eraLabel:"The Crum Dynasty", position:"SF", jerseyNumber:"20", ppg:4.5, rpg:3.5, apg:0.8, spg:0.0, bpg:0.0, rating:63, accolades:"1971-72 (stats from season logs)" },
  // ── Hickman Era: #20 ─────────────────────────────────────────────────────
  { id:"b-doutaz-20", name:"Bobby Doutaz", era:"hickman", eraLabel:"The Hickman Era", position:"PG", jerseyNumber:"20", ppg:6.0, rpg:2.5, apg:1.5, spg:0.0, bpg:0.0, rating:63, accolades:"1963-64 (stats from season logs)" },
  { id:"d-peloff", name:"Dick Peloff", era:"hickman", eraLabel:"The Hickman Era", position:"PG", jerseyNumber:"20", ppg:6.5, rpg:2.5, apg:2.0, spg:0.0, bpg:0.0, rating:64, accolades:"1960-62 (stats from season logs)" },
  { id:"r-tieman", name:"Roger Tieman", era:"hickman", eraLabel:"The Hickman Era", position:"PF", jerseyNumber:"20", ppg:6.0, rpg:5.0, apg:0.5, spg:0.0, bpg:0.0, rating:63, accolades:"1957-59 (stats from season logs)" },
  // ── Modern Era: #21 ──────────────────────────────────────────────────────
  { id:"s-curry", name:"Sydney Curry", era:"modern", eraLabel:"The Modern Era", position:"PF", jerseyNumber:"21", ppg:8.5, rpg:6.5, apg:0.8, spg:0.8, bpg:0.5, rating:70, accolades:"2021-23; physical interior presence" },
  { id:"c-minlend", name:"Charles Minlend", era:"modern", eraLabel:"The Modern Era", position:"SF", jerseyNumber:"21", ppg:7.0, rpg:4.5, apg:1.0, spg:1.0, bpg:0.3, rating:66, accolades:"2020-21 (transfer from UTSA)" },
  // ── Pitino Era: #21 ──────────────────────────────────────────────────────
  { id:"j-swopshire", name:"Jared Swopshire", era:"pitino", eraLabel:"The Pitino Era", position:"SF", jerseyNumber:"21", ppg:5.5, rpg:4.5, apg:1.0, spg:0.8, bpg:0.3, rating:65, accolades:"2008-12 (sat out one year)" },
  { id:"c-current", name:"Chris Current", era:"pitino", eraLabel:"The Pitino Era", position:"SF", jerseyNumber:"21", ppg:5.5, rpg:3.5, apg:1.0, spg:0.8, bpg:0.3, rating:64, accolades:"2003-07" },
  { id:"m-stone-21", name:"Marvin Stone", era:"pitino", eraLabel:"The Pitino Era", position:"C", jerseyNumber:"21", ppg:4.0, rpg:3.5, apg:0.3, spg:0.3, bpg:0.5, rating:62, accolades:"2002-03 season" },
  { id:"s-aaron", name:"Shaqquan Aaron", era:"pitino", eraLabel:"The Pitino Era", position:"SG", jerseyNumber:"21", ppg:4.0, rpg:1.5, apg:0.8, spg:0.5, bpg:0.1, rating:62, accolades:"2014-15 season" },
  { id:"t-cooper-21", name:"Tim Cooper", era:"crum", eraLabel:"The Crum Dynasty", position:"C", jerseyNumber:"21", ppg:4.5, rpg:4.0, apg:0.3, spg:0.0, bpg:0.0, rating:62, accolades:"1972-73 (stats from season logs)" },
  // ── Crum Era: #21 ────────────────────────────────────────────────────────
  { id:"r-wine", name:"Robby Wine", era:"crum", eraLabel:"The Crum Dynasty", position:"SF", jerseyNumber:"21", ppg:4.5, rpg:3.5, apg:0.8, spg:0.8, bpg:0.3, rating:63, accolades:"1992-96" },
  // ── Hickman Era: #21 ─────────────────────────────────────────────────────
  { id:"e-creamer", name:"Eddie Creamer", era:"hickman", eraLabel:"The Hickman Era", position:"SF", jerseyNumber:"21", ppg:7.5, rpg:4.0, apg:1.0, spg:0.0, bpg:0.0, rating:65, accolades:"1962-65 (stats from season logs)" },
  { id:"j-armstrong-21", name:"Jerry Armstrong", era:"hickman", eraLabel:"The Hickman Era", position:"PG", jerseyNumber:"21", ppg:6.0, rpg:2.5, apg:2.0, spg:0.0, bpg:0.0, rating:63, accolades:"1960-61 (stats from season logs)" },
  { id:"a-mantel", name:"Alex Mantel", era:"hickman", eraLabel:"The Hickman Era", position:"SG", jerseyNumber:"21", ppg:6.5, rpg:3.0, apg:1.0, spg:0.0, bpg:0.0, rating:64, accolades:"1957-59 (stats from season logs)" },
  { id:"h-hinton", name:"Harry Hinton", era:"hickman", eraLabel:"The Hickman Era", position:"PG", jerseyNumber:"21", ppg:5.5, rpg:2.5, apg:1.5, spg:0.0, bpg:0.0, rating:62, accolades:"1953-54 (stats from season logs)" },
  // ── Modern Era: #22 ──────────────────────────────────────────────────────
  { id:"a-igiehon", name:"Aidan Igiehon", era:"modern", eraLabel:"The Modern Era", position:"PF", jerseyNumber:"22", ppg:4.5, rpg:3.5, apg:0.8, spg:0.8, bpg:0.5, rating:63, accolades:"2019-21 (highly recruited)" },
  // ── Pitino Era: #22 ──────────────────────────────────────────────────────
  { id:"j-bond", name:"Jordan Bond", era:"pitino", eraLabel:"The Pitino Era", position:"SG", jerseyNumber:"22", ppg:3.0, rpg:1.5, apg:1.0, spg:0.5, bpg:0.1, rating:61, accolades:"2012-13 season" },
  { id:"c-millard", name:"Chad Millard", era:"pitino", eraLabel:"The Pitino Era", position:"SG", jerseyNumber:"22", ppg:2.5, rpg:1.5, apg:1.0, spg:0.3, bpg:0.1, rating:60, accolades:"2005-06 season" },
  { id:"e-justice", name:"Elisha Justice", era:"pitino", eraLabel:"The Pitino Era", position:"SG", jerseyNumber:"22", ppg:5.5, rpg:2.0, apg:2.5, spg:0.8, bpg:0.2, rating:65, accolades:"2010-12" },
  // ── Crum Era: #22 ────────────────────────────────────────────────────────
  { id:"c-mitchell-22", name:"Charlie Mitchell", era:"crum", eraLabel:"The Crum Dynasty", position:"SG", jerseyNumber:"22", ppg:5.0, rpg:2.5, apg:1.5, spg:0.0, bpg:0.0, rating:63, accolades:"1975-76 (stats from season logs)" },
  { id:"j-meiman", name:"Joe Meiman", era:"crum", eraLabel:"The Crum Dynasty", position:"SF", jerseyNumber:"22", ppg:6.0, rpg:3.5, apg:1.0, spg:0.0, bpg:0.0, rating:64, accolades:"1970-73 (stats from season logs)" },
  // ── Early/Dromo Era: #22 ──────────────────────────────────────────────────
  { id:"n-shields", name:"Nathan Shields", era:"early", eraLabel:"The Dromo Era", position:"SG", jerseyNumber:"22", ppg:5.5, rpg:2.0, apg:1.5, spg:0.0, bpg:0.0, rating:63, accolades:"1969-70 (stats from season logs)" },
  { id:"j-studer", name:"John Studer", era:"early", eraLabel:"The Dromo Era", position:"SG", jerseyNumber:"22", ppg:5.0, rpg:2.0, apg:1.0, spg:0.0, bpg:0.0, rating:62, accolades:"1968-69 (stats from season logs)" },
  { id:"s-king-22", name:"Steve King", era:"early", eraLabel:"The Dromo Era", position:"SG", jerseyNumber:"22", ppg:4.5, rpg:2.0, apg:1.0, spg:0.0, bpg:0.0, rating:62, accolades:"1967-68 (stats from season logs)" },
  // ── Hickman Era: #22 ─────────────────────────────────────────────────────
  { id:"d-clifford", name:"Dennis Clifford", era:"hickman", eraLabel:"The Hickman Era", position:"PF", jerseyNumber:"22", ppg:7.0, rpg:5.5, apg:0.8, spg:0.0, bpg:0.0, rating:65, accolades:"1962-65 (stats from season logs)" },
  // ── Modern Era: #23 ──────────────────────────────────────────────────────
  { id:"z-payne", name:"Zan Payne", era:"modern", eraLabel:"The Modern Era", position:"PG", jerseyNumber:"23", ppg:6.5, rpg:2.5, apg:3.0, spg:1.0, bpg:0.1, rating:66, accolades:"2022-24" },
  { id:"g-wiznitzer", name:"Gabe Wiznitzer", era:"modern", eraLabel:"The Modern Era", position:"PG", jerseyNumber:"23", ppg:4.0, rpg:1.5, apg:2.0, spg:0.5, bpg:0.1, rating:62, accolades:"2020-22" },
  { id:"s-enoch", name:"Steven Enoch", era:"modern", eraLabel:"The Modern Era", position:"C", jerseyNumber:"23", ppg:9.0, rpg:7.0, apg:0.5, spg:0.5, bpg:2.0, rating:76, accolades:"2018-20; ACC All-Defensive team 2020" },
  // ── Modern Era: #24 ──────────────────────────────────────────────────────
  { id:"c-hepburn", name:"Chucky Hepburn", era:"modern", eraLabel:"The Modern Era", position:"PG", jerseyNumber:"24", ppg:13.5, rpg:3.5, apg:4.5, spg:1.5, bpg:0.2, rating:76, accolades:"2024-25 (transfer from Wisconsin/Nebraska)" },
  // ── Pitino Era: #24 ──────────────────────────────────────────────────────
  { id:"l-whitehead", name:"Luke Whitehead", era:"pitino", eraLabel:"The Pitino Era", position:"PF", jerseyNumber:"24", ppg:4.5, rpg:3.5, apg:0.5, spg:0.5, bpg:0.5, rating:63, accolades:"2000-04" },
  // ── Crum Era: #24 ────────────────────────────────────────────────────────
  { id:"c-gervin", name:"Caleb Gervin", era:"crum", eraLabel:"The Crum Dynasty", position:"SG", jerseyNumber:"24", ppg:5.5, rpg:2.5, apg:1.5, spg:0.8, bpg:0.2, rating:64, accolades:"1999-2000 season" },
  { id:"c-farmer", name:"Craig Farmer", era:"crum", eraLabel:"The Crum Dynasty", position:"SG", jerseyNumber:"24", ppg:5.5, rpg:2.5, apg:1.5, spg:0.8, bpg:0.2, rating:64, accolades:"1994-98" },
  { id:"t-smith-24", name:"Troy Smith", era:"crum", eraLabel:"The Crum Dynasty", position:"SG", jerseyNumber:"24", ppg:5.0, rpg:2.5, apg:1.5, spg:0.8, bpg:0.2, rating:63, accolades:"1989-93" },
  { id:"w-olliges", name:"Will Olliges", era:"crum", eraLabel:"The Crum Dynasty", position:"PF", jerseyNumber:"24", ppg:6.0, rpg:5.0, apg:0.5, spg:0.5, bpg:0.5, rating:65, accolades:"1983-88" },
  { id:"s-bunton", name:"Stanley Bunton", era:"crum", eraLabel:"The Crum Dynasty", position:"C", jerseyNumber:"24", ppg:5.5, rpg:6.5, apg:0.5, spg:0.0, bpg:0.0, rating:65, accolades:"1973-77 (stats from season logs)" },
  { id:"p-pry", name:"Paul Pry", era:"crum", eraLabel:"The Crum Dynasty", position:"SG", jerseyNumber:"24", ppg:6.5, rpg:2.5, apg:1.5, spg:0.0, bpg:0.0, rating:65, accolades:"1969-72 (wore #24)" },
  // ── Modern Era: #25 ──────────────────────────────────────────────────────
  { id:"a-traore", name:"Aboubacar Traore", era:"modern", eraLabel:"The Modern Era", position:"C", jerseyNumber:"25", ppg:4.5, rpg:4.0, apg:0.3, spg:0.5, bpg:1.0, rating:63, accolades:"2024-25 season" },
  // ── Pitino Era: #25 ──────────────────────────────────────────────────────
  { id:"l-steiden", name:"Lee Steiden", era:"pitino", eraLabel:"The Pitino Era", position:"SF", jerseyNumber:"25", ppg:4.0, rpg:2.0, apg:0.8, spg:0.5, bpg:0.2, rating:62, accolades:"2007-09" },
  // ── Crum Era: #25 ────────────────────────────────────────────────────────
  { id:"j-osborne", name:"Jason Osborne", era:"crum", eraLabel:"The Crum Dynasty", position:"PG", jerseyNumber:"25", ppg:5.0, rpg:2.0, apg:2.5, spg:0.8, bpg:0.1, rating:63, accolades:"1993-96" },
  { id:"s-clark-25", name:"Steve Clark", era:"crum", eraLabel:"The Crum Dynasty", position:"SG", jerseyNumber:"25", ppg:5.5, rpg:2.5, apg:1.0, spg:0.0, bpg:0.0, rating:64, accolades:"1980-81 (stats from season logs)" },
  // ── Modern Era: #30 ──────────────────────────────────────────────────────
  { id:"a-myles", name:"Ashton Myles-Devore", era:"modern", eraLabel:"The Modern Era", position:"PF", jerseyNumber:"30", ppg:6.0, rpg:5.0, apg:0.8, spg:0.8, bpg:0.5, rating:65, accolades:"2020-23" },
  // ── Pitino Era: #30 ──────────────────────────────────────────────────────
  { id:"j-huffman", name:"Jonathan Huffman", era:"pitino", eraLabel:"The Pitino Era", position:"SF", jerseyNumber:"30", ppg:3.5, rpg:2.5, apg:0.8, spg:0.5, bpg:0.2, rating:62, accolades:"2005-07" },
  { id:"n-daniels", name:"Nate Daniels", era:"pitino", eraLabel:"The Pitino Era", position:"PF", jerseyNumber:"30", ppg:4.0, rpg:3.5, apg:0.5, spg:0.5, bpg:0.5, rating:62, accolades:"2003-04 season" },
  // ── Crum Era: #30 ────────────────────────────────────────────────────────
  { id:"d-dantzler", name:"Damion Dantzler", era:"crum", eraLabel:"The Crum Dynasty", position:"SF", jerseyNumber:"30", ppg:5.5, rpg:3.0, apg:1.5, spg:0.8, bpg:0.3, rating:64, accolades:"1996-98" },
  { id:"m-forrest", name:"Manuel Forrest", era:"crum", eraLabel:"The Crum Dynasty", position:"PF", jerseyNumber:"30", ppg:5.5, rpg:5.0, apg:0.5, spg:0.5, bpg:0.5, rating:65, accolades:"1981-85" },
  { id:"b-albertson", name:"Bob Albertson", era:"crum", eraLabel:"The Crum Dynasty", position:"PF", jerseyNumber:"30", ppg:5.0, rpg:5.0, apg:0.5, spg:0.0, bpg:0.0, rating:64, accolades:"1977-79 (stats from season logs)" },
  { id:"r-miles-30", name:"Rick Miles", era:"crum", eraLabel:"The Crum Dynasty", position:"PF", jerseyNumber:"30", ppg:4.5, rpg:4.5, apg:0.5, spg:0.0, bpg:0.0, rating:62, accolades:"1972-73 (stats from season logs)" },
  { id:"a-vilcheck", name:"Alan Vilcheck", era:"crum", eraLabel:"The Crum Dynasty", position:"PF", jerseyNumber:"30", ppg:6.5, rpg:5.5, apg:0.8, spg:0.0, bpg:0.0, rating:65, accolades:"1969-72 (stats from season logs)" },
  // ── Early Era: #30 ───────────────────────────────────────────────────────
  { id:"p-callahan", name:"Paul Callahan", era:"early", eraLabel:"The Dromo Era", position:"PF", jerseyNumber:"35", ppg:6.0, rpg:4.5, apg:0.8, spg:0.0, bpg:0.0, rating:64, accolades:"1967-69 (wore #30 then #35; stats from season logs)" },
  // ── Pitino Era: #32 ──────────────────────────────────────────────────────
  { id:"c-onuaku", name:"Chinanu Onuaku", era:"pitino", eraLabel:"The Pitino Era", position:"C", jerseyNumber:"32", ppg:7.5, rpg:6.5, apg:0.3, spg:0.3, bpg:2.0, rating:75, accolades:"2014-16; 2016 NBA 1st round pick (Houston Rockets)" },
  { id:"d-caracter", name:"Derrick Caracter", era:"pitino", eraLabel:"The Pitino Era", position:"C", jerseyNumber:"32", ppg:9.0, rpg:7.5, apg:0.5, spg:0.5, bpg:1.5, rating:73, accolades:"2006-08; 2010 NBA Draft pick" },
  // ── Crum Era: #32 ────────────────────────────────────────────────────────
  { id:"j-harmon", name:"Jerome Harmon", era:"crum", eraLabel:"The Crum Dynasty", position:"SF", jerseyNumber:"32", ppg:5.0, rpg:3.5, apg:0.8, spg:0.8, bpg:0.3, rating:63, accolades:"1988-90" },
  { id:"b-harmon-32", name:"Bill Harmon", era:"crum", eraLabel:"The Crum Dynasty", position:"SG", jerseyNumber:"32", ppg:5.5, rpg:2.5, apg:1.5, spg:0.0, bpg:0.0, rating:64, accolades:"1973-77 (stats from season logs)" },
  { id:"l-simmons", name:"Louis Simmons", era:"crum", eraLabel:"The Crum Dynasty", position:"PF", jerseyNumber:"32", ppg:4.5, rpg:4.5, apg:0.5, spg:0.0, bpg:0.0, rating:62, accolades:"1972-73 (stats from season logs)" },
  // ── Hickman Era: #32 ─────────────────────────────────────────────────────
  { id:"b-marin", name:"Bobby Marin", era:"hickman", eraLabel:"The Hickman Era", position:"SG", jerseyNumber:"32", ppg:7.0, rpg:3.5, apg:1.5, spg:0.0, bpg:0.0, rating:64, accolades:"1965-66 (stats from season logs)" },
  // ── Modern Era: #33 ──────────────────────────────────────────────────────
  { id:"a-mccool", name:"Aidan McCool", era:"modern", eraLabel:"The Modern Era", position:"SG", jerseyNumber:"33", ppg:7.5, rpg:2.5, apg:1.5, spg:1.0, bpg:0.2, rating:67, accolades:"2022-25" },
  { id:"m-cross", name:"Matt Cross", era:"modern", eraLabel:"The Modern Era", position:"SF", jerseyNumber:"33", ppg:5.0, rpg:3.5, apg:0.8, spg:0.8, bpg:0.3, rating:63, accolades:"2021-22 (transfer from Miami-OH)" },
  // ── Crum Era: #33 ────────────────────────────────────────────────────────
  { id:"t-kinnaird", name:"Tony Kinnaird", era:"crum", eraLabel:"The Crum Dynasty", position:"SF", jerseyNumber:"33", ppg:7.5, rpg:4.5, apg:1.5, spg:0.0, bpg:0.0, rating:69, accolades:"1973-79 (wore #22 '73-75, #33 '75-79; stats from season logs)" },
  // ── Crum Era: #44 ────────────────────────────────────────────────────────
  { id:"t-wingfield", name:"Tremaine Wingfield", era:"crum", eraLabel:"The Crum Dynasty", position:"PF", jerseyNumber:"44", ppg:5.5, rpg:5.5, apg:0.5, spg:0.8, bpg:0.5, rating:65, accolades:"1989-92" },

];

export type HistoricalSeason = {
  season: string;
  wins: number;
  losses: number;
  record: string;
  conference: string;
  postseason: string;
  champion: boolean;
  finalFour: boolean;
};

export const HISTORICAL_SEASONS: HistoricalSeason[] = [
  { season: "2024-25", wins: 27, losses: 8,  record: "27-8",  conference: "18-2 ACC",          postseason: "NCAA First Round",        champion: false, finalFour: false },
  { season: "2023-24", wins: 8,  losses: 24, record: "8-24",  conference: "3-17 ACC",           postseason: "",                        champion: false, finalFour: false },
  { season: "2022-23", wins: 4,  losses: 28, record: "4-28",  conference: "2-18 ACC",           postseason: "",                        champion: false, finalFour: false },
  { season: "2021-22", wins: 13, losses: 19, record: "13-19", conference: "6-14 AAC",           postseason: "",                        champion: false, finalFour: false },
  { season: "2020-21", wins: 13, losses: 7,  record: "13-7",  conference: "8-5 ACC",            postseason: "",                        champion: false, finalFour: false },
  { season: "2019-20", wins: 24, losses: 7,  record: "24-7",  conference: "15-5 ACC",           postseason: "COVID canceled",          champion: false, finalFour: false },
  { season: "2018-19", wins: 20, losses: 14, record: "20-14", conference: "10-8 ACC",           postseason: "NCAA First Round",        champion: false, finalFour: false },
  { season: "2017-18", wins: 22, losses: 14, record: "22-14", conference: "9-9 AAC",            postseason: "NIT Sweet 16",            champion: false, finalFour: false },
  { season: "2016-17", wins: 25, losses: 9,  record: "25-9",  conference: "12-6 ACC",           postseason: "NCAA Second Round",       champion: false, finalFour: false },
  { season: "2015-16", wins: 23, losses: 8,  record: "23-8",  conference: "12-6 ACC",           postseason: "",                        champion: false, finalFour: false },
  { season: "2014-15", wins: 27, losses: 9,  record: "27-9",  conference: "12-6 ACC",           postseason: "NCAA",                    champion: false, finalFour: false },
  { season: "2013-14", wins: 31, losses: 6,  record: "31-6",  conference: "15-3 AAC",           postseason: "NCAA",                    champion: false, finalFour: false },
  { season: "2012-13", wins: 35, losses: 5,  record: "35-5",  conference: "14-4 Big East",      postseason: "NCAA Champions",          champion: true,  finalFour: true  },
  { season: "2011-12", wins: 30, losses: 10, record: "30-10", conference: "10-8 Big East",      postseason: "NCAA Elite Eight",        champion: false, finalFour: false },
  { season: "2010-11", wins: 25, losses: 10, record: "25-10", conference: "12-6 Big East",      postseason: "NCAA Second Round",       champion: false, finalFour: false },
  { season: "2009-10", wins: 20, losses: 13, record: "20-13", conference: "11-7 Big East",      postseason: "NCAA First Round",        champion: false, finalFour: false },
  { season: "2008-09", wins: 31, losses: 6,  record: "31-6",  conference: "16-2 Big East",      postseason: "NCAA Elite Eight",        champion: false, finalFour: false },
  { season: "2007-08", wins: 27, losses: 9,  record: "27-9",  conference: "14-4 Big East",      postseason: "NCAA Elite Eight",        champion: false, finalFour: false },
  { season: "2006-07", wins: 24, losses: 10, record: "24-10", conference: "12-4 Big East",      postseason: "NCAA Second Round",       champion: false, finalFour: false },
  { season: "2005-06", wins: 21, losses: 13, record: "21-13", conference: "6-10 Big East",      postseason: "NIT Semifinals",          champion: false, finalFour: false },
  { season: "2004-05", wins: 33, losses: 5,  record: "33-5",  conference: "14-2 C-USA",         postseason: "NCAA Final Four",         champion: false, finalFour: true  },
  { season: "2003-04", wins: 20, losses: 10, record: "20-10", conference: "9-7 C-USA",          postseason: "NCAA First Round",        champion: false, finalFour: false },
  { season: "2002-03", wins: 25, losses: 7,  record: "25-7",  conference: "11-5 C-USA",         postseason: "NCAA Second Round",       champion: false, finalFour: false },
  { season: "2001-02", wins: 19, losses: 13, record: "19-13", conference: "8-8 C-USA",          postseason: "NIT Second Round",        champion: false, finalFour: false },
  { season: "2000-01", wins: 12, losses: 19, record: "12-19", conference: "8-8 C-USA",          postseason: "",                        champion: false, finalFour: false },
  { season: "1999-00", wins: 19, losses: 12, record: "19-12", conference: "10-6 C-USA",         postseason: "NCAA First Round",        champion: false, finalFour: false },
  { season: "1998-99", wins: 19, losses: 11, record: "19-11", conference: "11-5 C-USA",         postseason: "NCAA First Round",        champion: false, finalFour: false },
  { season: "1997-98", wins: 12, losses: 20, record: "12-20", conference: "5-11 C-USA",         postseason: "",                        champion: false, finalFour: false },
  { season: "1996-97", wins: 26, losses: 9,  record: "26-9",  conference: "9-5 C-USA",          postseason: "NCAA Elite Eight",        champion: false, finalFour: false },
  { season: "1995-96", wins: 22, losses: 12, record: "22-12", conference: "10-4 C-USA",         postseason: "NCAA Sweet 16",           champion: false, finalFour: false },
  { season: "1994-95", wins: 19, losses: 14, record: "19-14", conference: "7-5 Metro",          postseason: "NCAA First Round",        champion: false, finalFour: false },
  { season: "1993-94", wins: 28, losses: 6,  record: "28-6",  conference: "10-2 Metro",         postseason: "NCAA Sweet 16",           champion: false, finalFour: false },
  { season: "1992-93", wins: 22, losses: 9,  record: "22-9",  conference: "11-1 Metro",         postseason: "NCAA Sweet 16",           champion: false, finalFour: false },
  { season: "1991-92", wins: 19, losses: 11, record: "19-11", conference: "7-5 Metro",          postseason: "NCAA Second Round",       champion: false, finalFour: false },
  { season: "1990-91", wins: 14, losses: 16, record: "14-16", conference: "4-10 Metro",         postseason: "",                        champion: false, finalFour: false },
  { season: "1989-90", wins: 27, losses: 8,  record: "27-8",  conference: "12-2 Metro",         postseason: "NCAA Second Round",       champion: false, finalFour: false },
  { season: "1988-89", wins: 24, losses: 9,  record: "24-9",  conference: "8-4 Metro",          postseason: "NCAA Sweet 16",           champion: false, finalFour: false },
  { season: "1987-88", wins: 24, losses: 11, record: "24-11", conference: "9-3 Metro",          postseason: "NCAA Sweet 16",           champion: false, finalFour: false },
  { season: "1986-87", wins: 18, losses: 14, record: "18-14", conference: "9-3 Metro",          postseason: "",                        champion: false, finalFour: false },
  { season: "1985-86", wins: 32, losses: 7,  record: "32-7",  conference: "10-2 Metro",         postseason: "NCAA Champions",          champion: true,  finalFour: true  },
  { season: "1984-85", wins: 19, losses: 18, record: "19-18", conference: "6-8 Metro",          postseason: "NIT Semifinals",          champion: false, finalFour: false },
  { season: "1983-84", wins: 24, losses: 11, record: "24-11", conference: "11-3 Metro",         postseason: "NCAA Sweet 16",           champion: false, finalFour: false },
  { season: "1982-83", wins: 32, losses: 4,  record: "32-4",  conference: "14-0 Metro",         postseason: "NCAA Final Four",         champion: false, finalFour: true  },
  { season: "1981-82", wins: 23, losses: 10, record: "23-10", conference: "10-5 Metro",         postseason: "NCAA Final Four",         champion: false, finalFour: true  },
  { season: "1980-81", wins: 21, losses: 9,  record: "21-9",  conference: "13-1 Metro",         postseason: "NCAA Second Round",       champion: false, finalFour: false },
  { season: "1979-80", wins: 33, losses: 3,  record: "33-3",  conference: "14-0 Metro",         postseason: "NCAA Champions",          champion: true,  finalFour: true  },
  { season: "1978-79", wins: 24, losses: 8,  record: "24-8",  conference: "9-1 Metro",          postseason: "NCAA Sweet 16",           champion: false, finalFour: false },
  { season: "1977-78", wins: 23, losses: 7,  record: "23-7",  conference: "12-3 Metro",         postseason: "NCAA Sweet 16",           champion: false, finalFour: false },
  { season: "1976-77", wins: 21, losses: 7,  record: "21-7",  conference: "6-1 Metro",          postseason: "NCAA First Round",        champion: false, finalFour: false },
  { season: "1975-76", wins: 20, losses: 8,  record: "20-8",  conference: "2-2 Metro",          postseason: "NIT Second Round",        champion: false, finalFour: false },
  { season: "1974-75", wins: 28, losses: 3,  record: "28-3",  conference: "12-2 Missouri Val.", postseason: "NCAA Final Four",         champion: false, finalFour: true  },
  { season: "1973-74", wins: 21, losses: 7,  record: "21-7",  conference: "11-1 Missouri Val.", postseason: "NCAA Sweet 16",           champion: false, finalFour: false },
  { season: "1972-73", wins: 23, losses: 7,  record: "23-7",  conference: "11-3 Missouri Val.", postseason: "NIT Second Round",        champion: false, finalFour: false },
  { season: "1971-72", wins: 26, losses: 5,  record: "26-5",  conference: "12-2 Missouri Val.", postseason: "NCAA Final Four",         champion: false, finalFour: true  },
  { season: "1970-71", wins: 20, losses: 9,  record: "20-9",  conference: "9-5 Missouri Val.",  postseason: "NIT First Round",         champion: false, finalFour: false },
  { season: "1969-70", wins: 18, losses: 9,  record: "18-9",  conference: "11-5 Missouri Val.", postseason: "NIT First Round",         champion: false, finalFour: false },
  { season: "1968-69", wins: 21, losses: 6,  record: "21-6",  conference: "13-3 Missouri Val.", postseason: "NIT Second Round",        champion: false, finalFour: false },
  { season: "1967-68", wins: 21, losses: 7,  record: "21-7",  conference: "14-2 Missouri Val.", postseason: "NCAA Sweet 16",           champion: false, finalFour: false },
  { season: "1966-67", wins: 23, losses: 5,  record: "23-5",  conference: "12-2 Missouri Val.", postseason: "NCAA Sweet 16",           champion: false, finalFour: false },
];
