export type Position = "PG" | "SG" | "SF" | "PF" | "C";

export type Player = {
  id: string;
  name: string;
  era: string;
  eraLabel: string;
  position: Position;
  jerseyNumber: string;
  ppg: number;
  rpg: number;
  apg: number;
  spg: number;
  bpg: number;
  rating: number;
  accolades: string;
}

export const ERA_LABELS: Record<string, string> = {
  "1960s": "The Early Legends",
  "1970s": "The Crum Dynasty",
  "1980s": "The Crum Dynasty",
  "1990s": "The Crum Dynasty",
  "2000s": "The Pitino Revival",
  "2010s": "The Modern Era",
};

export const ALL_ERAS = ["1960s", "1970s", "1980s", "1990s", "2000s", "2010s"];

// Stats sourced from sports-reference.com/cbb — career per-game averages at Louisville
// Pre-1973 steals/blocks were not officially tracked; those are marked 0.0
export const PLAYERS: Player[] = [

  // ── 1960s ──────────────────────────────────────────────────────────────────
  {
    id: "w-unseld",
    name: "Wes Unseld",
    era: "1960s",
    eraLabel: "The Early Legends",
    position: "C",
    jerseyNumber: "31",
    ppg: 20.6,
    rpg: 18.9,
    apg: 2.5,
    spg: 0.0,
    bpg: 0.0,
    rating: 99,
    accolades: "2x Consensus All-American, 1968 NBA Draft #2"
  },
  {
    id: "w-wesley-cox",
    name: "Wesley Cox",
    era: "1960s",
    eraLabel: "The Early Legends",
    position: "SF",
    jerseyNumber: "25",
    ppg: 14.5,
    rpg: 7.2,
    apg: 1.8,
    spg: 0.0,
    bpg: 0.0,
    rating: 78,
    accolades: "MVC All-Conference"
  },

  // ── 1970s ──────────────────────────────────────────────────────────────────
  {
    id: "d-griffith",
    name: "Darrell Griffith",
    era: "1970s",
    eraLabel: "The Crum Dynasty",
    position: "SG",
    jerseyNumber: "35",
    ppg: 18.5,
    rpg: 4.6,
    apg: 3.0,
    spg: 2.0,
    bpg: 0.8,
    rating: 98,
    accolades: "1980 NCAA Champion, Wooden Award, NBA Draft #2"
  },
  {
    id: "j-bridgeman",
    name: "Junior Bridgeman",
    era: "1970s",
    eraLabel: "The Crum Dynasty",
    position: "SF",
    jerseyNumber: "10",
    ppg: 15.5,
    rpg: 7.6,
    apg: 2.7,
    spg: 0.9,
    bpg: 0.4,
    rating: 92,
    accolades: "2x MVC POY, 3x All-MVC, 1975 NBA Draft #8"
  },
  {
    id: "a-murphy",
    name: "Allen Murphy",
    era: "1970s",
    eraLabel: "The Crum Dynasty",
    position: "SF",
    jerseyNumber: "23",
    ppg: 16.3,
    rpg: 5.1,
    apg: 1.8,
    spg: 0.9,
    bpg: 1.1,
    rating: 88,
    accolades: "1975 Final Four, 2x All-MVC, 1975 NBA Draft #17"
  },
  {
    id: "t-howard",
    name: "Terry Howard",
    era: "1970s",
    eraLabel: "The Crum Dynasty",
    position: "SG",
    jerseyNumber: "14",
    ppg: 12.0,
    rpg: 3.0,
    apg: 2.0,
    spg: 0.8,
    bpg: 0.2,
    rating: 82,
    accolades: "1975 NCAA Final Four"
  },
  {
    id: "p-lanter",
    name: "Phil Bond",
    era: "1970s",
    eraLabel: "The Crum Dynasty",
    position: "PG",
    jerseyNumber: "12",
    ppg: 10.8,
    rpg: 3.1,
    apg: 5.2,
    spg: 1.1,
    bpg: 0.1,
    rating: 80,
    accolades: "1980 NCAA Champion, Metro POY"
  },
  {
    id: "l-williams-70",
    name: "Larry Williams",
    era: "1970s",
    eraLabel: "The Crum Dynasty",
    position: "PF",
    jerseyNumber: "42",
    ppg: 11.3,
    rpg: 7.8,
    apg: 1.2,
    spg: 0.6,
    bpg: 0.9,
    rating: 78,
    accolades: "All-MVC Honorable Mention"
  },

  // ── 1980s ──────────────────────────────────────────────────────────────────
  {
    id: "p-ellison",
    name: "Pervis Ellison",
    era: "1980s",
    eraLabel: "The Crum Dynasty",
    position: "C",
    jerseyNumber: "43",
    ppg: 15.8,
    rpg: 8.4,
    apg: 2.4,
    spg: 1.3,
    bpg: 2.8,
    rating: 96,
    accolades: "1986 NCAA Champion & MOP, 1989 NBA Draft #1"
  },
  {
    id: "m-wagner",
    name: "Milt Wagner",
    era: "1980s",
    eraLabel: "The Crum Dynasty",
    position: "PG",
    jerseyNumber: "13",
    ppg: 12.8,
    rpg: 2.5,
    apg: 3.0,
    spg: 1.0,
    bpg: 0.4,
    rating: 88,
    accolades: "1986 NCAA Champion, 1983 All-American"
  },
  {
    id: "l-smith",
    name: "LaBradford Smith",
    era: "1980s",
    eraLabel: "The Crum Dynasty",
    position: "SG",
    jerseyNumber: "21",
    ppg: 13.6,
    rpg: 2.9,
    apg: 5.4,
    spg: 1.7,
    bpg: 0.1,
    rating: 89,
    accolades: "HS Parade AA, 1991 NBA Draft #19"
  },
  {
    id: "b-thompson",
    name: "Billy Thompson",
    era: "1980s",
    eraLabel: "The Crum Dynasty",
    position: "SF",
    jerseyNumber: "5",
    ppg: 11.8,
    rpg: 6.5,
    apg: 3.2,
    spg: 0.8,
    bpg: 1.3,
    rating: 89,
    accolades: "1986 NCAA Champion & All-American, 1986 NBA Draft #19"
  },
  {
    id: "d-smith-80",
    name: "Derek Smith",
    era: "1980s",
    eraLabel: "The Crum Dynasty",
    position: "SG",
    jerseyNumber: "43",
    ppg: 13.9,
    rpg: 6.7,
    apg: 1.9,
    spg: 1.1,
    bpg: 0.5,
    rating: 89,
    accolades: "1980 NCAA Champion, 1982 All-American, Metro POY"
  },
  {
    id: "h-crook",
    name: "Herbert Crook",
    era: "1980s",
    eraLabel: "The Crum Dynasty",
    position: "PF",
    jerseyNumber: "4",
    ppg: 10.7,
    rpg: 6.4,
    apg: 2.1,
    spg: 0.8,
    bpg: 0.5,
    rating: 82,
    accolades: "1986 NCAA Champion"
  },

  // ── 1990s ──────────────────────────────────────────────────────────────────
  {
    id: "d-wheat",
    name: "DeJuan Wheat",
    era: "1990s",
    eraLabel: "The Crum Dynasty",
    position: "PG",
    jerseyNumber: "32",
    ppg: 16.1,
    rpg: 2.6,
    apg: 3.7,
    spg: 1.5,
    bpg: 0.2,
    rating: 93,
    accolades: "1997 All-CUSA, HS Parade AA, 1997 NBA Draft"
  },
  {
    id: "c-rozier",
    name: "Clifford Rozier",
    era: "1990s",
    eraLabel: "The Crum Dynasty",
    position: "PF",
    jerseyNumber: "44",
    ppg: 17.0,
    rpg: 11.0,
    apg: 1.8,
    spg: 1.0,
    bpg: 1.8,
    rating: 91,
    accolades: "1994 Consensus All-American, 2x Metro POY, NBA Draft #16"
  },
  {
    id: "s-walker",
    name: "Samaki Walker",
    era: "1990s",
    eraLabel: "The Crum Dynasty",
    position: "C",
    jerseyNumber: "54",
    ppg: 14.3,
    rpg: 7.3,
    apg: 1.2,
    spg: 0.7,
    bpg: 2.4,
    rating: 87,
    accolades: "HS Parade AA, 1996 NBA Draft #9"
  },
  {
    id: "e-slay",
    name: "Eric Slay",
    era: "1990s",
    eraLabel: "The Crum Dynasty",
    position: "SG",
    jerseyNumber: "12",
    ppg: 11.3,
    rpg: 3.4,
    apg: 2.4,
    spg: 1.4,
    bpg: 0.2,
    rating: 80,
    accolades: "C-USA All-Freshman, All-CUSA Honorable Mention"
  },
  {
    id: "a-watkins",
    name: "Alvin Watkins",
    era: "1990s",
    eraLabel: "The Crum Dynasty",
    position: "SF",
    jerseyNumber: "33",
    ppg: 10.8,
    rpg: 5.7,
    apg: 1.6,
    spg: 1.0,
    bpg: 0.6,
    rating: 78,
    accolades: "Metro Conference All-Freshman"
  },

  // ── 2000s ──────────────────────────────────────────────────────────────────
  {
    id: "r-gaines",
    name: "Reece Gaines",
    era: "2000s",
    eraLabel: "The Pitino Revival",
    position: "SG",
    jerseyNumber: "22",
    ppg: 15.6,
    rpg: 3.4,
    apg: 3.8,
    spg: 1.5,
    bpg: 0.2,
    rating: 91,
    accolades: "2x All-CUSA, 2003 NBA Draft #15"
  },
  {
    id: "f-garcia",
    name: "Francisco Garcia",
    era: "2000s",
    eraLabel: "The Pitino Revival",
    position: "SF",
    jerseyNumber: "32",
    ppg: 14.4,
    rpg: 3.9,
    apg: 3.5,
    spg: 1.5,
    bpg: 1.4,
    rating: 90,
    accolades: "CUSA ROY, 3x All-CUSA, 2005 NBA Draft #23"
  },
  {
    id: "t-williams-00",
    name: "Terrence Williams",
    era: "2000s",
    eraLabel: "The Pitino Revival",
    position: "SF",
    jerseyNumber: "1",
    ppg: 11.2,
    rpg: 6.9,
    apg: 3.9,
    spg: 1.5,
    bpg: 0.6,
    rating: 89,
    accolades: "3x All-Big East, 2009 NBA Draft #11"
  },
  {
    id: "e-sosa",
    name: "Edgar Sosa",
    era: "2000s",
    eraLabel: "The Pitino Revival",
    position: "PG",
    jerseyNumber: "10",
    ppg: 9.7,
    rpg: 1.8,
    apg: 2.8,
    spg: 0.8,
    bpg: 0.1,
    rating: 80,
    accolades: "2007 Big East All-Freshman, Big East Tourney champion"
  },
  {
    id: "j-palacios",
    name: "Juan Palacios",
    era: "2000s",
    eraLabel: "The Pitino Revival",
    position: "PF",
    jerseyNumber: "3",
    ppg: 8.9,
    rpg: 5.7,
    apg: 1.3,
    spg: 0.9,
    bpg: 0.4,
    rating: 79,
    accolades: "2005 All-CUSA, Big East Honorable Mention"
  },
  {
    id: "d-padgett-00",
    name: "David Padgett",
    era: "2000s",
    eraLabel: "The Pitino Revival",
    position: "C",
    jerseyNumber: "4",
    ppg: 8.8,
    rpg: 5.1,
    apg: 1.6,
    spg: 0.5,
    bpg: 1.2,
    rating: 80,
    accolades: "Big East All-Tournament Team 2005"
  },

  // ── 2010s ──────────────────────────────────────────────────────────────────
  {
    id: "r-smith",
    name: "Russ Smith",
    era: "2010s",
    eraLabel: "The Modern Era",
    position: "PG",
    jerseyNumber: "2",
    ppg: 14.3,
    rpg: 2.7,
    apg: 2.8,
    spg: 1.9,
    bpg: 0.1,
    rating: 95,
    accolades: "2013 NCAA Champion, 2x All-American ('Russdiculous')"
  },
  {
    id: "p-siva",
    name: "Peyton Siva",
    era: "2010s",
    eraLabel: "The Modern Era",
    position: "PG",
    jerseyNumber: "3",
    ppg: 8.4,
    rpg: 2.4,
    apg: 4.7,
    spg: 1.8,
    bpg: 0.1,
    rating: 89,
    accolades: "2013 NCAA Champion, 2x All-Big East Tourney MVP"
  },
  {
    id: "d-mitchell",
    name: "Donovan Mitchell",
    era: "2010s",
    eraLabel: "The Modern Era",
    position: "SG",
    jerseyNumber: "45",
    ppg: 11.7,
    rpg: 4.1,
    apg: 2.2,
    spg: 1.5,
    bpg: 0.3,
    rating: 90,
    accolades: "2017 All-ACC, 2017 NBA Draft #13, 5x NBA All-Star"
  },
  {
    id: "m-harrell",
    name: "Montrezl Harrell",
    era: "2010s",
    eraLabel: "The Modern Era",
    position: "PF",
    jerseyNumber: "24",
    ppg: 11.6,
    rpg: 6.9,
    apg: 0.9,
    spg: 0.8,
    bpg: 1.1,
    rating: 91,
    accolades: "2013 NCAA Champion, 2015 Karl Malone Award"
  },
  {
    id: "g-dieng",
    name: "Gorgui Dieng",
    era: "2010s",
    eraLabel: "The Modern Era",
    position: "C",
    jerseyNumber: "10",
    ppg: 8.3,
    rpg: 7.9,
    apg: 1.2,
    spg: 1.0,
    bpg: 2.6,
    rating: 88,
    accolades: "2013 NCAA Champion, Big East DPOY, NBA Draft #21"
  },
  {
    id: "l-hancock",
    name: "Luke Hancock",
    era: "2010s",
    eraLabel: "The Modern Era",
    position: "SF",
    jerseyNumber: "11",
    ppg: 10.1,
    rpg: 2.6,
    apg: 1.8,
    spg: 1.0,
    bpg: 0.1,
    rating: 85,
    accolades: "2013 Final Four MOP, 2013 NCAA Champion"
  },
  {
    id: "k-kuric",
    name: "Kyle Kuric",
    era: "2010s",
    eraLabel: "The Modern Era",
    position: "SG",
    jerseyNumber: "14",
    ppg: 8.3,
    rpg: 3.2,
    apg: 0.9,
    spg: 1.0,
    bpg: 0.3,
    rating: 80,
    accolades: "2013 NCAA Champion, 2012 All-Big East"
  },
];
